In [314]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")
ids_conversaciones_ignorar = []

In [315]:
sentencia = "SELECT * FROM conversations WHERE EXTRACT(MONTH from created_at) = 11"
df = pd.read_sql(sentencia, engine)

df['created_at'] = pd.to_datetime(df['created_at'])

#df['weekday'] = df['created_at'].dt.weekday

# sabados = df[df['weekday'] == 5]
# domingos = df[df['weekday'] == 6]

df_laboral = df[(df['created_at'].dt.weekday < 5) |  ( (df['created_at'].dt.weekday == 5) &  (df['created_at'].dt.hour < 12))]

#df_laboral= df_laboral[~df_laboral['id'].isin(ids_conversaciones_ignorar)]
conversaciones_por_dia = df_laboral.groupby(df_laboral['created_at'].dt.to_period('D')).size()



promedio_conversaciones_diarias = conversaciones_por_dia.mean()
promedio_conversaciones_diarias


# df_laboral['created_at'].dt.weekday.unique()
# df['created_at'].dt.weekday.unique()


#1ro noviembre

np.float64(95.08333333333333)

In [316]:
sentencia_messages_invalidos = "SELECT * FROM messages WHERE sender_type IS NULL"
df_messages_invalidos = pd.read_sql(sentencia_messages_invalidos, engine)
ids_invalidos = df_messages_invalidos['conversation_id'].unique()
ids_conversaciones_ignorar = ids_invalidos.tolist()


sentencia_messages = "SELECT * FROM messages" #Preguntar por mensajes(content) vacios
#SELECT * FROM messages WHERE sender_type IS NOT NULL AND sender_type != 'User'
#SELECT * FROM messages WHERE sender_type IS NOT NULL AND message_type = 0
df_messages = pd.read_sql(sentencia_messages, engine)
mensajes_por_hora = df_messages.groupby(df_messages['created_at'].dt.to_period('h')).size()
promedio_mensajes_por_hora = mensajes_por_hora.mean().round(2)

promedio_mensajes_por_hora
df_messages.head()

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
0,9820,¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,1,1,736,1,2025-11-13 13:03:58.917519,2025-11-13 13:03:58.917519,False,0,None,0,None,User,6.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,{}
1,9822,Arteriografia periferica de una extremidad inf...,1,1,741,0,2025-11-13 13:04:26.560786,2025-11-13 13:04:26.560786,False,0,None,0,None,Contact,216.0,None,{},Arteriografia periferica de una extremidad inf...,{}
2,9830,ofrecemos disculpas presentamos una actualizac...,1,1,736,1,2025-11-13 13:05:03.718563,2025-11-13 13:05:03.718563,False,0,None,0,None,User,6.0,None,{},ofrecemos disculpas presentamos una actualizac...,{}
3,9837,Uretrografia retrograda,1,1,743,0,2025-11-13 13:05:48.827515,2025-11-13 13:05:48.827515,False,0,None,0,None,Contact,319.0,None,{},Uretrografia retrograda,{}
4,9838,",24920134",1,1,742,0,2025-11-13 13:05:50.872601,2025-11-13 13:05:50.872601,False,0,None,0,None,Contact,318.0,None,{},",24920134",{}

In [317]:
sentencia_message2 = "SELECT * FROM messages WHERE conversation_id = 736"

df_messages2 = pd.read_sql(sentencia_message2, engine)

df_messages2.head(15)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
0,9820,¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,1,1,736,1,2025-11-13 13:03:58.917519,2025-11-13 13:03:58.917519,False,0,None,0,None,User,6.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,{}
1,9830,ofrecemos disculpas presentamos una actualizac...,1,1,736,1,2025-11-13 13:05:03.718563,2025-11-13 13:05:03.718563,False,0,None,0,None,User,6.0,None,{},ofrecemos disculpas presentamos una actualizac...,{}
2,9821,Por favor podría responder a mi solicitud,1,1,736,0,2025-11-13 13:04:21.153461,2025-11-13 13:04:21.153461,False,0,None,0,None,Contact,315.0,None,{},Por favor podría responder a mi solicitud,{}
3,9824,Ayer me dijeron para agendar cita para el sába...,1,1,736,0,2025-11-13 13:04:53.534174,2025-11-13 13:04:53.534174,False,0,None,0,None,Contact,315.0,None,{},Ayer me dijeron para agendar cita para el sába...,{}
4,9857,,1,1,736,0,2025-11-13 13:07:36.847836,2025-11-13 13:07:36.847836,False,0,None,0,None,Contact,315.0,None,{},,{}
5,9871,Para el sábado correcto?,1,1,736,0,2025-11-13 13:09:52.939943,2025-11-13 13:09:52.939943,False,0,None,0,None,Contact,315.0,None,{},Para el sábado correcto?,{}
6,9876,nos informabas ayer que el paciente tolera sin...,1,1,736,1,2025-11-13 13:10:35.243301,2025-11-13 13:10:35.243301,False,0,None,0,None,User,6.0,None,{},nos informabas ayer que el paciente tolera sin...,{}
7,9934,La conversación fue marcada por Andrés Echeverri,1,1,736,2,2025-11-13 13:20:00.146381,2025-11-13 13:20:00.146381,False,0,None,0,None,None,NaN,None,{},La conversación fue marcada por Andrés Echeverri,{}
8,9936,Andrés Echeverri agregó agendamiento_exitoso,1,1,736,2,2025-11-13 13:20:28.621423,2025-11-13 13:20:28.621423,False,0,None,0,None,None,NaN,None,{},Andrés Echeverri agregó agendamiento_exitoso,{}
9,9848,"Para programar su cita, por favor indíquenos l...",1,1,736,0,2025-11-13 13:06:56.253019,2025-11-13 13:06:56.253019,False,0,None,0,None,Contact,315.0,None,{},"Para programar su cita, por favor indíquenos l...",{}
10,9854,Por la complejidad del procedimiento solicitad...,1,1,736,0,2025-11-13 13:07:15.109979,2025-11-13 13:07:15.109979,False,0,None,0,None,Contact,315.0,None,{},Por la complejidad del procedimiento solicitad...,{}
11,9851,Mathias Sebastian zambrano Marquez\r\n\r\nPt 5...,1,1,736,0,2025-11-13 13:07:04.146012,2025-11-13 13:07:04.146012,False,0,None,0,None,Contact,315.0,None,{},Mathias Sebastian zambrano Marquez\r\n\r\nPt 5...,{}
12,9855,No\r\n\r\nNo\r\n\r\nNo\r\n\r\n42kg\r\n\r\nNo\r...,1,1,736,0,2025-11-13 13:07:25.202454,2025-11-13 13:07:25.202454,False,0,None,0,None,Contact,315.0,None,{},No\r\n\r\nNo\r\n\r\nNo\r\n\r\n42kg\r\n\r\nNo\r...,{}
13,9863,muchas gracias ya le envío el soporte de su cita,1,1,736,1,2025-11-13 13:08:45.525222,2025-11-13 13:08:45.525222,False,0,None,0,None,User,6.0,None,{},muchas gracias ya le envío el soporte de su cita,{}
14,9869,Perfecto muchas gracias 🫂,1,1,736,0,2025-11-13 13:09:18.303985,2025-11-13 13:09:18.303985,False,0,None,0,None,Contact,315.0,None,{},Perfecto muchas gracias 🫂,{}

In [334]:
# df['created_at'] = pd.to_datetime(df['created_at']).dt.tz_localize('UTC')
# df['first_reply_created_at'] = pd.to_datetime(df['first_reply_created_at']).dt.tz_localize('UTC')

df['created_at'] = df['created_at'].dt.tz_convert('America/Bogota')
df['first_reply_created_at'] = df['first_reply_created_at'].dt.tz_convert('America/Bogota')



mismo_dia = df['created_at'].dt.date == df['first_reply_created_at'].dt.date
def calcular_dia_distinto(row):
    inicio = row['created_at']
    
    fin = row['first_reply_created_at']


    segundos = 0
    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    if inicio < fin_laboral:
        segundos +=(fin_laboral-inicio).total_seconds()
    
    inicio_laboral = fin.replace(hour=7, minute=0, second=0, microsecond=0)

    if fin > inicio_laboral:
        segundos +=(fin - inicio_laboral).total_seconds()
    
    return max(segundos, 0)

df['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    (df['first_reply_created_at']-df['created_at']).dt.total_seconds().round(2),
    df.apply(calcular_dia_distinto, axis=1)
)



df['tiempo_respuesta_minutos'] = (df['tiempo_respuesta_segundos'] / 60).round(2)
df['tiempo_respuesta_horas'] = (df['tiempo_respuesta_minutos'] / 60).round(2)

df.head()
# df_sessions['duracion_session_min'] = ((df_sessions['end_time']-df_sessions['start_time']).dt.total_seconds() / 60).round(2)
# df_sessions['duracion_session_horas'] = df_sessions['duracion_session_min'] / 60

,id,account_id,inbox_id,status,assignee_id,created_at,updated_at,contact_id,display_id,contact_last_seen_at,...,custom_attributes,assignee_last_seen_at,first_reply_created_at,priority,sla_policy_id,waiting_since,cached_label_list,tiempo_respuesta_segundos,tiempo_respuesta_minutos,tiempo_respuesta_horas
0,519,1,1,1,10.0,2025-11-07 16:13:15.714864-05:00,2025-11-08 20:06:35.877442,176,519,None,...,{},2025-11-08 16:42:40.368080,2025-11-08 09:00:51.596234-05:00,0.0,None,NaT,agendamiento,10055.88137,167.60,2.79
1,1536,1,1,1,1.0,2025-11-19 14:48:58.922063-05:00,2025-11-20 12:15:55.444572,864,1536,None,...,{},2025-11-20 12:10:44.301156,2025-11-19 14:48:58.926667-05:00,NaN,None,NaT,iniciada_con_plantilla,0.00000,0.00,0.00
2,681,1,1,1,10.0,2025-11-12 08:22:26.752159-05:00,2025-11-12 13:24:34.362754,193,681,None,...,{},2025-11-12 13:24:34.437282,2025-11-12 08:23:27.318889-05:00,0.0,None,NaT,,60.57000,1.01,0.02
3,810,1,1,1,12.0,2025-11-13 12:05:37.028843-05:00,2025-11-13 17:11:15.160128,373,810,None,...,{},2025-11-13 17:11:15.244229,2025-11-13 12:08:55.052780-05:00,0.0,None,NaT,,198.02000,3.30,0.06
4,347,1,1,1,NaN,2025-11-04 11:30:54.797194-05:00,2025-11-04 16:40:54.064708,13,347,None,...,{},2025-11-04 16:40:54.135637,2025-11-04 11:31:21.708632-05:00,0.0,None,NaT,,26.91000,0.45,0.01