In [3]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import holidays
import re
engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")

# Metrica #1. Promedio Diario de Conversaciones

In [14]:
sentencia = "SELECT * FROM conversations WHERE created_at >= '2025-11-01'"

year_rp = 2025
month_rp = 12

co_holidays = holidays.Colombia(years=year_rp)
co_holidays_dt = pd.to_datetime(list(co_holidays))

df = pd.read_sql(sentencia, engine)
df['created_at'] = pd.to_datetime(df['created_at'])

df = df[(df['created_at'].dt.year == year_rp) & (df['created_at'].dt.month == month_rp)]
df = df.sort_values(['id', 'created_at'])

df['holiday'] = df['created_at'].dt.normalize().isin(co_holidays_dt)

contactos = pd.read_sql("SELECT * FROM contacts WHERE name ~ '[A-Za-z]'", engine)
ids_ignorar_contactos = contactos['id'].unique()
ids_ignorar_contactos = ids_ignorar_contactos.tolist()

cantidad_datos_sin_filtrar = len(df)

ids_conversaciones_ignorar = df.loc[df['contact_id'].isin(ids_ignorar_contactos), 'id']

ids_sin_first_reply_created_at = df.loc[df['first_reply_created_at'].isna(), 'id']
ids_conversaciones_ignorar = pd.concat([ids_conversaciones_ignorar, ids_sin_first_reply_created_at]).unique()

cantidad_conversaciones_ignoradas_contactos = df['id'].isin(ids_conversaciones_ignorar).sum()

df = df[~df['id'].isin(ids_conversaciones_ignorar)]

cantidad_conversaciones_festivos = df[df['holiday']]


df = df[~df['holiday']]
cantidad_datos_filtrados = len(df)
df['weekday'] = df['created_at'].dt.weekday
promedios_24_h = (
    df.groupby([df['weekday'], df['created_at'].dt.to_period('D')]).size().groupby(level=0).mean().round(2)
)

print(f"Cantidad datos antes de ignorar: {cantidad_datos_sin_filtrar}")
print(f"Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: {cantidad_conversaciones_ignoradas_contactos}")
print(f"Cantidad conversaciones ignoradas por festivos: {len(cantidad_conversaciones_festivos)}")

print(f"Cantidad datos despues de ignorar: {cantidad_datos_filtrados}\n")

print(f"Anio: {year_rp} - Mes: {month_rp}")
print(f"Promedios conversaciones del mes 24h: \n")
print(f"Lunes: {promedios_24_h[0]}")
print(f"Martes: {promedios_24_h[1]}")
print(f"Miercoles: {promedios_24_h[2]}")
print(f"Jueves: {promedios_24_h[3]}")
print(f"Viernes: {promedios_24_h[4]}")
print(f"Sabado: {promedios_24_h[5]}")
print(f"Domingo: {promedios_24_h[6]} \n")

print("Promedios hora laboral")

df_habiles = df.copy()


df_habiles = df_habiles[
    ((df_habiles['weekday'] != 6) & (df_habiles['weekday'] != 5) & (df_habiles['created_at'].dt.hour >=12) & (df_habiles['created_at'].dt.hour <=22)) | (
        (df_habiles['weekday'] == 5) &
        (df_habiles['created_at'].dt.hour >= 13) &
        (df_habiles['created_at'].dt.hour <= 17)
    )
]

promedios = (
    df_habiles.groupby([df_habiles['weekday'], df_habiles['created_at'].dt.to_period('D')])
    .size()
    .groupby(level=0) 
    .mean()
    .round(2)
)

ids_conversaciones_validas = df['id'].unique()

print(f"Lunes: {promedios[0]}")
print(f"Martes: {promedios[1]}")
print(f"Miercoles: {promedios[2]}")
print(f"Jueves: {promedios[3]}")
print(f"Viernes: {promedios[4]}")
print(f"Sabado: {promedios[5]}")

Cantidad datos antes de ignorar: 2620
Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: 188
Cantidad conversaciones ignoradas por festivos: 13
Cantidad datos despues de ignorar: 2419

Anio: 2025 - Mes: 12
Promedios conversaciones del mes 24h:

Lunes: 141.5
Martes: 110.6
Miercoles: 83.0
Jueves: 127.67
Viernes: 91.25
Sabado: 28.25
Domingo: 8.0

Promedios hora laboral
Lunes: 135.75
Martes: 103.8
Miercoles: 76.0
Jueves: 118.33
Viernes: 84.0
Sabado: 22.25

# Metrica  #2. Promedio de mensajes por hora

In [15]:
## metrica nueva: mensajes por hora que mande cada agente

sentencia_messages = "SELECT * FROM messages WHERE created_at >= '2025-11-01'" 
df_all_messages = pd.read_sql(sentencia_messages, engine)

df_messages = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages = df_messages.sort_values(['conversation_id', 'created_at'])


msg_agnts = df_messages[(df_messages['sender_type'].notna()) & (df_messages['sender_type'] == 'User') & (df_messages['sender_id'] != 1) & (df_messages['sender_id'] != 11)].copy()
df_messages = df_messages[(df_messages['sender_type'].notna()) & (df_messages['sender_type'] != 'User')]

df_messages['weekday'] = df_messages['created_at'].dt.weekday

promedios_por_hora_24h = (df_messages.groupby([df_messages['weekday'], df_messages['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))

print(f"Total mensajes de contactos en el mes: {len(df_messages)}\n")
print(f"Promedio mensajes de contactos en las 24h:")
print(f"Lunes: {promedios_por_hora_24h[0]}")
print(f"Martes: {promedios_por_hora_24h[1]}")
print(f"Miercoles: {promedios_por_hora_24h[2]}")
print(f"Jueves: {promedios_por_hora_24h[3]}")
print(f"Viernes: {promedios_por_hora_24h[4]}")
print(f"Sabado: {promedios_por_hora_24h[5]}")
print(f"Sabado: {promedios_por_hora_24h[6]} \n")


df_habiles_messag = df_messages[
    ((df_messages['weekday'] != 6) & (df_messages['weekday'] != 5) & (df_messages['created_at'].dt.hour >=12) & (df_messages['created_at'].dt.hour <=22)) | (
        (df_messages['weekday'] == 5) &
        (df_messages['created_at'].dt.hour >= 13) &
        (df_messages['created_at'].dt.hour <= 17)
    )
]
promedios_por_hora = (df_habiles_messag.groupby([df_habiles_messag['weekday'], df_habiles_messag['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))

print(f"Promedio mensajes de contactos en horario laboral:")
print(f"Lunes:{promedios_por_hora[0]}")
print(f"Martes: {promedios_por_hora[1]}")
print(f"Miercoles: {promedios_por_hora[2]}")
print(f"Jueves: {promedios_por_hora[3]}")
print(f"Viernes: {promedios_por_hora[4]}")
print(f"Sabado: {promedios_por_hora[5]}")

Total mensajes de contactos en el mes: 14461

Promedio mensajes de contactos en las 24h:
Lunes: 49.61
Martes: 42.65
Miercoles: 32.81
Jueves: 43.15
Viernes: 34.42
Sabado: 15.85
Sabado: 2.22

Promedio mensajes de contactos en horario laboral:
Lunes:68.5
Martes: 62.38
Miercoles: 49.2
Jueves: 68.15
Viernes: 50.23
Sabado: 30.32

# Mensajes por hora que manda cada agente

In [34]:
msg_agnts['weekday'] = msg_agnts['created_at'].dt.weekday

msg_agnts_hr = msg_agnts.groupby([msg_agnts['weekday'], msg_agnts['sender_id'], msg_agnts['created_at'].dt.to_period('h')]).size().groupby(level=1).mean()
msg_agnts['hour'] = msg_agnts['created_at'].dt.hour

msg_agnts_hr = (
    msg_agnts
    .groupby(['sender_id', 'weekday', 'hour'])
    .size()
    .groupby(['sender_id', 'weekday'])
    .mean().round(2)
)

total = msg_agnts_hr.sum()
total

msg_agnts_hr

# v = msg_agnts[(msg_agnts['sender_type'] == 'User') & (msg_agnts['sender_id'] == 6) & (msg_agnts['weekday'] == 0)].copy()
# v.shape

sender_id  weekday
6.0        0          130.00
           1          140.27
           2           96.55
           3           93.27
           4           76.36
           5           98.25
9.0        1            1.00
           2           10.00
           3            1.00
           4            1.00
10.0       0           87.45
           1          101.64
           2           79.82
           3           67.27
           4           83.18
           5           56.20
12.0       0           40.50
           1           68.82
           2           54.27
           3           39.64
           4           31.40
           5           31.25
14.0       0            1.00
           1            1.67
           2            1.80
           3            1.75
           4            2.20
15.0       0            2.00
           4           17.00
dtype: float64

## Hacer el promedio de primera respuesta solo de conversaciones que se crearon dentro del horario laboral

In [ ]:
# Promedio de primera respuesta de conversaciones que se iniciaron en cualquier hora y se calcula dependiendo de la la hora de la primera respuesta
# Por ejemplo: primer mensaje de usuario: miercoles 7pm; primera respuesta: 8:30am. Tiempo de primera respuesta = 90min


# Promedio de primera respuesta de conversaciones que se iniciaron solo en horario laboral, ignorando domingos, festivos y conversaciones que se crearon por fuera del horario laboral
# En este caso el ejemplo de arriba no aplica aqui porque la conversacion no se debe tomar en cuenta

# Metrica #3 Tiempo de Primera Respuesta

In [12]:
##Promedio primera respuesta de cada agente
##Promedio de todos los mensajes de cada agente 

df_sin_inicio_plantilla = df[~df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False)].copy()

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_localize('UTC')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_localize('UTC')

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_convert('America/Bogota')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia = df_sin_inicio_plantilla['created_at'].dt.date == df_sin_inicio_plantilla['first_reply_created_at'].dt.date

def calcular_dia_distinto(row):
    inicio = row['created_at']
    primera_respuesta = row['first_reply_created_at']

    segundos = 0

    inicio_laboral_create_at = inicio.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    inicio_laboral_first_reply = primera_respuesta.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        inicio_laboral_create_at = inicio.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
      
    if row['first_reply_created_at'].weekday() == 5:
        inicio_laboral_first_reply = primera_respuesta.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral_create_at and inicio < fin_laboral_created_at and row['created_at'].weekday() != 6:
        segundos +=(fin_laboral_created_at-inicio).total_seconds()
    
    if primera_respuesta > inicio_laboral_first_reply:
        segundos +=(primera_respuesta - inicio_laboral_first_reply).total_seconds()
    
    return segundos

def calcular_mismo_dia(row):
    inicio = row['created_at']
    primera_respuesta = row['first_reply_created_at']

    segundos = 0

    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)
    inicio_laboral = primera_respuesta.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        fin_laboral = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
        inicio_laboral = primera_respuesta.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral and inicio < fin_laboral :
        segundos +=(primera_respuesta-inicio).total_seconds()
    
    if inicio < inicio_laboral and primera_respuesta <= fin_laboral:
        segundos +=(primera_respuesta-inicio_laboral).total_seconds()
    
    return max(segundos, 0)
    
df_sin_inicio_plantilla['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    df_sin_inicio_plantilla.apply(calcular_mismo_dia, axis=1).round(2),
    df_sin_inicio_plantilla.apply(calcular_dia_distinto, axis=1).round(2)
)

df_sin_inicio_plantilla['tiempo_respuesta_minutos'] = (df_sin_inicio_plantilla['tiempo_respuesta_segundos'] / 60).round(2)
df_sin_inicio_plantilla['tiempo_respuesta_horas'] = (df_sin_inicio_plantilla['tiempo_respuesta_minutos'] / 60).round(2)

promedio_tiempo_respuesta_min = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].mean()

print(df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe())

df_sin_inicio_plantilla

count    1253.000000
mean       45.813966
std        41.296678
min         0.100000
25%        14.650000
50%        33.440000
75%        67.100000
max       278.630000
Name: tiempo_respuesta_minutos, dtype: float64

,id,account_id,inbox_id,status,assignee_id,created_at,updated_at,contact_id,display_id,contact_last_seen_at,...,first_reply_created_at,priority,sla_policy_id,waiting_since,cached_label_list,holiday,weekday,tiempo_respuesta_segundos,tiempo_respuesta_minutos,tiempo_respuesta_horas
5182,5385,1,1,1,NaN,2026-01-01 19:20:45.816212-05:00,2026-01-03 15:39:53.708784,3210,5385,None,...,2026-01-02 07:22:49.418219-05:00,0.0,None,NaT,serivicios_y_tarifas,False,4,1369.42,22.82,0.38
5041,5386,1,1,1,NaN,2026-01-02 04:42:10.852914-05:00,2026-01-05 12:11:09.303477,3211,5386,None,...,2026-01-02 07:23:20.736038-05:00,0.0,None,NaT,agendamiento,False,4,1400.74,23.35,0.39
5116,5398,1,1,1,10.0,2026-01-02 07:23:40.161925-05:00,2026-01-02 12:49:40.657727,3213,5398,None,...,2026-01-02 07:31:24.853212-05:00,0.0,None,NaT,,False,4,464.69,7.74,0.13
5128,5399,1,1,1,NaN,2026-01-02 07:24:06.324594-05:00,2026-01-02 13:10:54.890887,3214,5399,None,...,2026-01-02 07:34:55.950086-05:00,0.0,None,NaT,"agendamiento, agendamiento_exitoso",False,4,649.63,10.83,0.18
5205,5400,1,1,1,NaN,2026-01-02 07:28:56.089496-05:00,2026-01-02 17:46:44.164128,1414,5400,None,...,2026-01-02 07:35:32.445375-05:00,0.0,None,NaT,agendamiento_exitoso,False,4,396.36,6.61,0.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6614,7035,1,1,0,NaN,2026-01-19 13:26:57.499419-05:00,2026-01-19 19:00:23.232907,2473,7035,None,...,2026-01-19 14:00:20.095664-05:00,0.0,None,NaT,agendamiento,False,0,2002.60,33.38,0.56
6568,7036,1,1,0,13.0,2026-01-19 13:36:19.000649-05:00,2026-01-19 18:42:41.980752,4226,7036,None,...,2026-01-19 13:38:30.531474-05:00,0.0,None,NaT,serivicios_y_tarifas,False,0,131.53,2.19,0.04
6583,7037,1,1,0,13.0,2026-01-19 13:45:11.461305-05:00,2026-01-19 18:49:20.244471,4227,7037,None,...,2026-01-19 13:46:00.482763-05:00,0.0,None,2026-01-19 18:49:20.237247,agendamiento,False,0,49.02,0.82,0.01
6578,7039,1,1,1,13.0,2026-01-19 13:52:43.901115-05:00,2026-01-19 18:59:36.584827,4090,7039,None,...,2026-01-19 13:54:45.598826-05:00,0.0,None,NaT,resultados,False,0,121.70,2.03,0.03
6581,7041,1,1,0,13.0,2026-01-19 13:56:11.076791-05:00,2026-01-19 19:02:27.626419,4229,7041,None,...,2026-01-19 13:59:12.385512-05:00,0.0,None,2026-01-19 19:01:14.312476,serivicios_y_tarifas,False,0,181.31,3.02,0.05

## Promedio primera respuesta conversaciones iniciadas con plantilla

In [96]:
# ids_caso_raro = [6175, 6877, 6214, 6057]
ids_conv_iniciadas_plantilla = df.loc[df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False),'id']

#ids_conv_iniciadas_plantilla = ids_conv_iniciadas_plantilla[~ids_conv_iniciadas_plantilla.isin(ids_caso_raro)]

df_messages_conv_ini_plantilla = df_all_messages[df_all_messages['conversation_id'].isin(ids_conv_iniciadas_plantilla)].copy()
df_messages_conv_ini_plantilla = df_messages_conv_ini_plantilla.sort_values(['conversation_id', 'created_at'])

primer_mensaje_contacto = df_messages_conv_ini_plantilla[(df_messages_conv_ini_plantilla['message_type'] == 0) & (~df_messages_conv_ini_plantilla['content'].isin(['system_resolved', 'system_timeout']))].groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'created_at_type_0'})

df_merge_tiempo_primer_mensaje_contacto = df_messages_conv_ini_plantilla.merge(primer_mensaje_contacto, on='conversation_id', how='inner')

df_mensajes_agente = df_merge_tiempo_primer_mensaje_contacto[
    (df_merge_tiempo_primer_mensaje_contacto['message_type'] == 1) &
    (df_merge_tiempo_primer_mensaje_contacto['private'] != True) &
    (df_merge_tiempo_primer_mensaje_contacto['created_at'] > df_merge_tiempo_primer_mensaje_contacto['created_at_type_0'])
]

df_primera_respuesta = (df_mensajes_agente.sort_values(['conversation_id', 'created_at']).groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'first_reply_created_at'}))

df_first_messages = primer_mensaje_contacto.merge(df_primera_respuesta,on='conversation_id',how='left')
df_first_messages = df_first_messages.rename(columns={'created_at_type_0': 'created_at'})

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_localize('UTC')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_localize('UTC')

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_convert('America/Bogota')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia_plantilla =  df_first_messages['created_at'].dt.date == df_first_messages['first_reply_created_at'].dt.date
df_first_messages['tiempo_respuesta_minutos'] = np.where(
    mismo_dia_plantilla,
    (df_first_messages.apply(calcular_mismo_dia, axis=1) / 60).round(2),
    (df_first_messages.apply(calcular_dia_distinto, axis=1) / 60).round(2)
)

promedio = df_first_messages['tiempo_respuesta_minutos'].mean() 

total_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].sum()
cantidad_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].count()

total_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].count()

promedio_total = ((total_inicio_plantilla + total_sin_inicio_plantilla) / (cantidad_inicio_plantilla + cantidad_sin_inicio_plantilla)).round(2)
promedio_total

np.float64(44.13)

# Promedio primera respuesta conversaciones iniciadas solo en horario laboral

In [97]:
df_filtrado_sin_plantilla = df_sin_inicio_plantilla[
    (
        df_sin_inicio_plantilla['created_at'].dt.weekday.between(0, 4) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_sin_inicio_plantilla['created_at'].dt.weekday == 5) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(8, 11)
    )
]

total_minutos_df_filtrado_sin_pl = df_filtrado_sin_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_df_filtrado_sin_pl = df_filtrado_sin_plantilla['tiempo_respuesta_minutos'].count()


promedio_laboral_sin_pl = df_filtrado_sin_plantilla['tiempo_respuesta_minutos'].mean()


df_filtrado_solo_pl = df_first_messages[
     (
        df_first_messages['created_at'].dt.weekday.between(0, 4) &
        df_first_messages['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_first_messages['created_at'].dt.weekday == 5) &
        df_first_messages['created_at'].dt.hour.between(8, 11)
    )
]
total_minutos_df_solo_pl = df_filtrado_solo_pl['tiempo_respuesta_minutos'].sum()
cantidad_df_filtrado_solo_pl = df_filtrado_solo_pl['tiempo_respuesta_minutos'].count()

promedio_laboral = (total_minutos_df_filtrado_sin_pl + total_minutos_df_solo_pl) / (cantidad_df_filtrado_sin_pl+cantidad_df_filtrado_solo_pl)
promedio_laboral

np.float64(42.73432893716058)

# Metrica #4. Tiempo Promedio de Respuesta

Mediana del tiempo entre mensajes usuario → agente durante conversaciones activas.

In [ ]:
#promedio de todo
sentencia_messages_contact_user = "SELECT * FROM messages WHERE created_at >= '2025-11-01'"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])
df_messages_contact_user = df_messages_contact_user[df_messages_contact_user['conversation_id'].isin(ids_conversaciones_validas)]

df_messages_contact_user['next_message_type'] = df_messages_contact_user.groupby('conversation_id')['message_type'].shift(-1)
df_messages_contact_user['next_created_at'] = df_messages_contact_user.groupby('conversation_id')['created_at'].shift(-1)

respuestas = df_messages_contact_user[
    (df_messages_contact_user['message_type'] == 0) &
    (df_messages_contact_user['next_message_type'] == 1)
].copy()

mismo_dia_respuestas = respuestas['created_at'].dt.date == respuestas['next_created_at'].dt.date

def medir_dia_distinto(row):
    created_at = row['created_at']

    next_created_at = row['next_created_at']

    inicio_laboral_created_at = created_at.replace(hour=12, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = created_at.replace(hour=22, minute=0, second=0, microsecond=0)

    inicio_laboral_next = next_created_at.replace(hour=13, minute=0, second=0, microsecond=0)
    fin_laboral_next = next_created_at.replace(hour=17, minute=0, second=0, microsecond=0)
    if created_at.weekday() == 5:
        inicio_laboral_created_at = created_at.replace(hour=13, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = created_at.replace(hour=17, minute=0, second=0, microsecond=0)

    if next_created_at.weekday() == 5:
        inicio_laboral_next = next_created_at.replace(hour=13, minute=0, second=0, microsecond=0)
        fin_laboral_next = next_created_at.replace(hour=17, minute=0, second=0, microsecond=0)

    segundos = 0
    if created_at >= inicio_laboral_created_at and created_at <= fin_laboral_created_at:
        segundos += (fin_laboral_created_at - created_at).total_seconds()
    
    if next_created_at >= inicio_laboral_next and next_created_at <= fin_laboral_next:
        segundos += (next_created_at - inicio_laboral_next).total_seconds()

    return max(segundos, 0)

def medir_mismo_dia(row):
    created_at = row['created_at']

    next_created_at = row['next_created_at']

    inicio_laboral_created_at = created_at.replace(hour=12, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = created_at.replace(hour=22, minute=0, second=0, microsecond=0)
    
    segundos = 0
    if created_at >= inicio_laboral_created_at and created_at <= fin_laboral_created_at:
        segundos += (next_created_at - created_at).total_seconds()
    else:
        segundos += (next_created_at - inicio_laboral_created_at).total_seconds()

    return max(segundos, 0)

respuestas['response_time_minutes'] = np.where(
    mismo_dia_respuestas,
    (respuestas.apply(medir_mismo_dia, axis=1) / 60).round(2),
    (respuestas.apply(medir_dia_distinto, axis=1) / 60).round(2)
)

promedio_por_conversacion = (respuestas.groupby('conversation_id')['response_time_minutes'].mean()).round(2) 

promedio_por_conversacion

conversation_id
5385    29.82
5386    46.50
5388     7.30
5389    20.13
5391    12.81
        ...
7035    31.07
7036     1.62
7037     0.34
7039     1.76
7041     1.96
Name: response_time_minutes, Length: 1426, dtype: float64

# Metrica #5. Conversión agendamiento (%)

In [ ]:
#de todas las conversaciones que existen que porcentaje es agendamiento exitoso
#de todas las q existen

df_iniciadas_agendamiento = df[
    df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

agendamiento_exitoso = df_iniciadas_agendamiento[df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

iniciada_agendamiento = df_iniciadas_agendamiento[~df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

porcentaje_agendamiento_exitoso = (len(agendamiento_exitoso) / len(df_iniciadas_agendamiento)) * 100
porcentaje_agendamiento_no_exitoso = (len(iniciada_agendamiento) / len(df_iniciadas_agendamiento)) * 100

df_no_iniciadas_agendamiento = df[
    ~df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

no_iniciadas_agendamiento_agendadas = df_no_iniciadas_agendamiento[df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

no_iniciadas_agendamiento_no_agendadas = df_no_iniciadas_agendamiento[~df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

len(no_iniciadas_agendamiento_no_agendadas)

porcentaje_no_iniciadas_agendamiento_agendadas = (len(no_iniciadas_agendamiento_agendadas) / len(df_no_iniciadas_agendamiento)) * 100
porcentaje_no_iniciadas_agendamiento_agendadas

27.064676616915424

# Metrica #7. Índice de Eficiencia del Agente (AEI) [0–100] (Hacer mas adelante cuando se perfeccione la metrica de primera respuesta)

In [ ]:
df = df.sort_values(['assignee_id'])
ids_contacts = df['contact_id'].unique()
df = df.sort_values(['contact_id'])
df.head()

# Metrica #9. Utilización de Capacidad (%)

In [100]:
# Nombre de cada agente (Imprimir bien los resultados)

plantilla = [
    '¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A.', 
    'Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda. ¿Podemos ayudarle en algo más?', 
    '¡Con gusto! Procederemos a cancelar su cita, por favor, envíanos los siguientes datos para gestionar mejor nuestra agenda y su solicitud.',
    'Recuerde que su lugar de atención es: Centro De Especialistas De Risaralda, Carrera 5 No 18-33,',
    'Para programar su cita, por favor indíquenos los siguientes datos:',
    'Lamentamos la demora en nuestra respuesta. Ayer enfrentamos una contingencia, pero ya estamos atendiendo su solicitud. ¡Gracias por su paciencia!',
    '¡Gracias por elegirnos! 💙 Esperamos poder atenderte nuevamente. Feliz día🌞 En caso de requerir algo adicional, escríbenos en cualquier momento. ¡Estamos para servirte! 😊',
    'Por la complejidad del procedimiento solicitado y su seguridad, requerimos que por favor, nos confirme los siguientes datos:', 
    '📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge',
    '📌 Para la solicitud y agendamientos de exámenes de Hemodinamia, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3128345850.',
    'nuestros horarios de atención son de lunes a viernes de 7:00 a.m a 5:00 p.m sabados de 8:00 a.m a 12:00 pm domingos y festivos cerrado',
    'IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comunicación y el interés en nuestros servicios.',
    '⌛ "Agradecemos su paciencia. Actualmente estamos recibiendo un volumen de usuarios mayor al habitual, por lo que estamos atendiendo los mensajes por orden de llegada.',
    'Nos permitimos informar que, para la solicitud y consulta de sus resultados',
    '¡Con gusto! Procederemos a reprogramar su cita, por favor, envíanos los siguientes datos para gestionar mejor nuestra agenda y su solicitud.'     
]

df_messages_agent = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages_agent = df_messages_agent[
    ((df_messages_agent['created_at'].dt.weekday != 6) & (df_messages_agent['created_at'].dt.weekday != 5) & (df_messages_agent['created_at'].dt.hour >=12) & (df_messages_agent['created_at'].dt.hour <=22)) | (
        (df_messages_agent['created_at'].dt.weekday == 5) &
        (df_messages_agent['created_at'].dt.hour >= 13) &
        (df_messages_agent['created_at'].dt.hour <= 17)
    )
]

df_messages_agent = df_messages_agent[(df_messages_agent['sender_type'] == 'User') & (df_messages_agent['sender_id'] != 1)  & (df_messages_agent['sender_id'] != 11)]

df_messages_agent = df_messages_agent.sort_values(['conversation_id', 'created_at'])

ppm = 40        

df_messages_agent['cantidad_palabras'] = df_messages_agent['content'].fillna("").str.split().str.len()

df_messages_agent['tiempo_minutos_mensaje'] = (df_messages_agent['cantidad_palabras'] / ppm)

df_messages_agent['created_at'] = pd.to_datetime(df_messages_agent['created_at'])

df_messages_agent['content'] = df_messages_agent['content'].astype(str)

plantillas_escaped = [re.escape(p) for p in plantilla] 

patron = "|".join(plantillas_escaped)
df_messages_agent = df_messages_agent[~df_messages_agent['content'].str.contains(patron, na=False)]

cantidad_segundos_diarios = (
    df_messages_agent
    .groupby([
        df_messages_agent['created_at'].dt.date, 
        'sender_id'
    ])['tiempo_minutos_mensaje'].sum().round(2)
)

cantidad_segundos_diarios.head(20)
# df_prueba_agent = df_messages_agent[(df_messages_agent['sender_id'] == 11) & (df_messages_agent['created_at'].dt.day == 5)]
# df_prueba_agent

# suma = df_prueba_agent['tiempo_minutos_mensaje'].sum() 
# suma

created_at  sender_id
2026-01-02  6.0           48.70
            10.0          39.62
            12.0          20.30
2026-01-03  10.0          31.35
            12.0           7.50
2026-01-05  6.0           67.70
            10.0          73.05
            12.0          31.78
2026-01-06  6.0           38.88
            10.0          65.22
            12.0          43.82
2026-01-07  6.0          104.95
            9.0            0.40
            10.0          65.08
            12.0          45.98
2026-01-08  6.0           72.68
            10.0          54.88
            12.0          50.10
2026-01-09  6.0           57.15
            10.0          60.70
Name: tiempo_minutos_mensaje, dtype: float64

In [56]:
agentes_asis = df_messages_agent[df_messages_agent['created_at'].dt.day == 5]['sender_id'].unique()
agentes_asis

array([10.,  6., 12., 11.])

### Celula consultar datos

In [ ]:
ids_caso_raro = [6175, 6877, 6214, 6057]
sentencia_messages_contact_user = "SELECT * FROM messages WHERE id = 1038"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine) 

df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_localize('UTC')
df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_convert('America/Bogota')

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])

df_messages_contact_user.head(90)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
0,1038,"📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3155311608 y/o al teléfono al 606 3320000.",1,1,122,1,2025-06-24 16:12:25.896861-05:00,2025-06-24 21:12:25.896861,False,0,None,0,None,None,None,None,{},"📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3155311608 y/o al teléfono al 606 3320000.",{}