In [ ]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import holidays
import re
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')
import seaborn as sns
engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")
engine2 = create_engine("postgresql+psycopg2://intern:internpass@localhost:5433/intern_db")


year_rp = 2025
month_rp = 11

start_day = 1
end_day = 30

# Metrica #1. Promedio Diario de Conversaciones

In [2]:
sentencia = "SELECT * FROM conversations WHERE created_at >= '2025-11-01'"


co_holidays = holidays.Colombia(years=year_rp)
co_holidays_dt = pd.to_datetime(list(co_holidays))

df = pd.read_sql(sentencia, engine)
df['created_at'] = pd.to_datetime(df['created_at'])

df = df[
    (df['created_at'].dt.year == year_rp) & 
    (df['created_at'].dt.month == month_rp) & 
    (df['created_at'].dt.day >= start_day) & 
    (df['created_at'].dt.day <= end_day)
] 
df = df.sort_values(['id', 'created_at'])

df['holiday'] = df['created_at'].dt.normalize().isin(co_holidays_dt)

contactos = pd.read_sql("SELECT * FROM contacts WHERE name ~ '[A-Za-z]'", engine)
ids_ignorar_contactos = contactos['id'].unique()
ids_ignorar_contactos = ids_ignorar_contactos.tolist()

cantidad_datos_sin_filtrar = len(df)

ids_conversaciones_ignorar = df.loc[df['contact_id'].isin(ids_ignorar_contactos), 'id']

ids_sin_first_reply_created_at = df.loc[df['first_reply_created_at'].isna(), 'id']
ids_conversaciones_ignorar = pd.concat([ids_conversaciones_ignorar, ids_sin_first_reply_created_at]).unique()

cantidad_conversaciones_ignoradas_contactos = df['id'].isin(ids_conversaciones_ignorar).sum()

df = df[~df['id'].isin(ids_conversaciones_ignorar)]

cantidad_conversaciones_festivos = df[df['holiday']]


df = df[~df['holiday']]
cantidad_datos_filtrados = len(df)
df['weekday'] = df['created_at'].dt.weekday
promedios_24_h = (
    df.groupby([df['weekday'], df['created_at'].dt.to_period('D')])
    .size()
    .groupby(level=0)
    .mean()
    .round(2)
)
df_promedios_semanal = promedios_24_h.reset_index()
df_promedios_semanal.columns = ['weekday', 'promedio_conversaciones']

mapa_dias = {
    0: "lunes",
    1: "martes",
    2: "miercoles",
    3: "jueves",
    4: "viernes",
    5: "sabado",
    6: "domingo"
}

df_promedios_semanal["dia"] = df_promedios_semanal["weekday"].map(mapa_dias)

df_promedios_semanal = df_promedios_semanal[["dia", "promedio_conversaciones"]]

print(f"Cantidad datos antes de ignorar: {cantidad_datos_sin_filtrar}")
print(f"Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: {cantidad_conversaciones_ignoradas_contactos}")
print(f"Cantidad conversaciones ignoradas por festivos: {len(cantidad_conversaciones_festivos)}")

print(f"Cantidad datos despues de ignorar: {cantidad_datos_filtrados}\n")

# print(f"Anio: {year_rp} - Mes: {month_rp}")
# print(f"Promedios conversaciones del mes 24h: \n")
# print(f"Lunes: {promedios_24_h[0]}")
# print(f"Martes: {promedios_24_h[1]}")
# print(f"Miercoles: {promedios_24_h[2]}")
# print(f"Jumsg_agntseves: {promedios_24_h[3]}")
# print(f"Viernes: {promedios_24_h[4]}")
# print(f"Sabado: {promedios_24_h[5]}")
# print(f"Domingo: {promedios_24_h[6]} \n")

# print("Promedios hora laboral")

ids_conversaciones_validas = df['id'].unique()

df_promedios_semanal

Cantidad datos antes de ignorar: 2416
Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: 305
Cantidad conversaciones ignoradas por festivos: 9
Cantidad datos despues de ignorar: 2102

         dia  promedio_conversaciones
0      lunes                    110.5
1     martes                    112.0
2  miercoles                    102.0
3     jueves                    120.0
4    viernes                    103.0
5     sabado                     31.0
6    domingo                      4.5

# Metrica  #2. Promedio de mensajes por hora

In [17]:
sentencia_messages = "SELECT * FROM messages WHERE created_at >= '2025-11-01'" 
df_all_messages = pd.read_sql(sentencia_messages, engine)

df_messages = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages = df_messages.sort_values(['conversation_id', 'created_at'])


msg_agnts = df_messages[
    (df_messages['sender_type'].notna()) & 
    (df_messages['sender_type'] == 'User') & 
    (df_messages['sender_id'] != 1) & 
    (df_messages['sender_id'] != 11) & 
    (df_messages['sender_id'] != 14) &
    (df_messages['sender_id'] != 9)
    ].copy()
df_messages_contact = df_messages[(df_messages['sender_type'].notna()) & (df_messages['sender_type'] != 'User')].copy()

df_messages_contact['created_at'] = df_messages_contact['created_at'].dt.tz_localize('UTC')
df_messages_contact['created_at'] = df_messages_contact['created_at'].dt.tz_convert('America/Bogota')

df_messages_contact['weekday'] = df_messages_contact['created_at'].dt.weekday
df_messages_contact['hour'] = df_messages_contact['created_at'].dt.hour
df_messages_contact['date'] = df_messages_contact['created_at'].dt.date


conteo_dias = (
    df_messages_contact.groupby(['weekday', 'date', 'hour'])
    .size()
    .reset_index(name='conteo')
)
promedio_por_hora = (
    conteo_dias
    .groupby(['weekday', 'hour'])['conteo']
    .mean()
    .round(2)
)
promedio_por_hora.head(30)

tabla = promedio_por_hora.unstack(level=0)


tabla = tabla.rename(columns=mapa_dias)

tabla = tabla.reset_index()

tabla = tabla.sort_values("hour")
tabla = tabla.fillna(0)
tabla

weekday  hour  lunes  martes  miercoles  jueves  viernes  sabado  domingo
0           1   0.00    0.00       0.00    0.00     1.00    0.00      0.0
1           3   0.00    2.00       0.00    0.00     0.00    0.00      0.0
2           4   0.00    0.00       0.00    0.00     0.00    2.00      0.0
3           5   0.00    2.00       0.00    0.00     0.00    1.00      0.0
4           6   2.50    4.00       1.75    3.67     1.67    2.50      0.0
5           7  29.33   27.75      30.25   59.50    38.25    2.33      1.0
6           8  51.50   57.50      57.50  110.50    61.50   30.00      0.0
7           9  56.67   63.75      55.25   88.00    65.00   36.00      1.0
8          10  64.33   66.75      63.50   85.00    76.75   37.50      4.5
9          11  87.00   61.50      64.50   81.75    70.50   63.75      0.0
10         12  53.00   32.75      37.00   60.33    48.00    4.33      1.0
11         13  62.50   47.00      34.75   50.50    43.50    1.00      1.0
12         14  42.00   62.00      47.00   80.25    63.25    3.00      1.0
13         15  78.00   81.50      59.25   78.25    59.50    0.00      5.0
14         16  75.50   69.25      44.50   77.50    50.25    0.00      0.0
15         17  14.00   35.75      32.75   36.50    27.00    0.00      0.0
16         18   4.00    7.00       8.00    2.67     5.33    0.00      0.0
17         19   2.00    7.50       1.67    3.67     2.00    0.00      0.0
18         20   3.00    1.50       2.00    8.67     2.50    0.00      0.0
19         21   2.50    3.50       1.00    3.00     2.00    0.00      2.0
20         22   2.00    1.50       1.00    4.00     1.00    0.00      0.0
21         23   0.00    0.00       2.00    4.50     2.00    0.00      0.0

# Mensajes por hora que manda cada agente

In [30]:
# msg_agnts['created_at'] = msg_agnts['created_at'].dt.tz_localize('UTC')
msg_agnts['created_at'] = msg_agnts['created_at'].dt.tz_convert('America/Bogota')
msg_agnts['weekday'] = msg_agnts['created_at'].dt.weekday

msg_agnts['hour'] = msg_agnts['created_at'].dt.hour
msg_agnts['date'] = msg_agnts['created_at'].dt.date

conteo_diario_agente = (
    msg_agnts.groupby(['sender_id', 'weekday', 'date'])
    .size()
    .reset_index(name='mensajes_dia')
)

def horas_laborales(weekday):
    if weekday <= 4:  
        return 8
    elif weekday == 5:
        return 5
    else:            
        return 0
    
conteo_diario_agente['horas_laborales'] = (
    conteo_diario_agente['weekday'].apply(horas_laborales)
)
conteo_diario_agente['mensajes_por_hora'] = (
    conteo_diario_agente['mensajes_dia'] /
    conteo_diario_agente['horas_laborales']
)
promedio_por_dia_agente = (
    conteo_diario_agente
    .groupby(['sender_id', 'weekday'])['mensajes_por_hora']
    .mean()
    .round(2)
    .reset_index()
)

promedio_por_dia_agente["dia"] = (
    promedio_por_dia_agente["weekday"].map(mapa_dias)
)

agentes = {
    6: 'Andres echeverry',
    10: 'Viviana',
    12: 'Jenny',
    13: 'Edwar',
    15: 'Diana',
}

promedio_por_dia_agente["sender_id"] = promedio_por_dia_agente["sender_id"].map(agentes).fillna(promedio_por_dia_agente["sender_id"])
promedio_por_dia_agente = promedio_por_dia_agente[['sender_id', 'mensajes_por_hora', 'dia']]


tabla_agentes = promedio_por_dia_agente.pivot(
    index='dia', 
    columns='sender_id',
    values='mensajes_por_hora'
).fillna(0)

orden_dias = ["lunes", "martes", "miercoles", "jueves", "viernes", "sabado"]
tabla_agentes = tabla_agentes.reindex(orden_dias).reset_index()

tabla_agentes
tabla_agentes


#Agregar a Joan

sender_id        dia  Andres echeverry  Diana  Edwar  Jenny  Viviana
0              lunes             19.50  25.00  11.25  18.88    16.12
1             martes             19.55  14.71   0.00  12.21    26.62
2          miercoles             15.19  14.58   0.88  18.34    17.09
3             jueves             32.75  20.00   8.62  23.78    20.31
4            viernes             34.96  12.62   7.38  13.59    26.59
5             sabado             41.80   8.00   0.00  30.00    20.13

# Metrica #3 Tiempo de Primera Respuesta

In [33]:

df_sin_inicio_plantilla = df[~df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False)].copy()

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_localize('UTC')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_localize('UTC')

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_convert('America/Bogota')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia = df_sin_inicio_plantilla['created_at'].dt.date == df_sin_inicio_plantilla['first_reply_created_at'].dt.date

def calcular_dia_distinto(row):
    inicio = row['created_at']
    primera_respuesta = row['first_reply_created_at']

    segundos = 0

    inicio_laboral_create_at = inicio.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    inicio_laboral_first_reply = primera_respuesta.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        inicio_laboral_create_at = inicio.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
      
    if row['first_reply_created_at'].weekday() == 5:
        inicio_laboral_first_reply = primera_respuesta.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral_create_at and inicio < fin_laboral_created_at and row['created_at'].weekday() != 6:
        segundos +=(fin_laboral_created_at-inicio).total_seconds()
    
    if primera_respuesta > inicio_laboral_first_reply:
        segundos +=(primera_respuesta - inicio_laboral_first_reply).total_seconds()
    
    return segundos

def calcular_mismo_dia(row):
    inicio = row['created_at']
    primera_respuesta = row['first_reply_created_at']

    segundos = 0

    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)
    inicio_laboral = primera_respuesta.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        fin_laboral = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
        inicio_laboral = primera_respuesta.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral and inicio < fin_laboral :
        segundos +=(primera_respuesta-inicio).total_seconds()
    
    if inicio < inicio_laboral and primera_respuesta <= fin_laboral:
        segundos +=(primera_respuesta-inicio_laboral).total_seconds()
    
    return max(segundos, 0)
    
df_sin_inicio_plantilla['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    df_sin_inicio_plantilla.apply(calcular_mismo_dia, axis=1).round(2),
    df_sin_inicio_plantilla.apply(calcular_dia_distinto, axis=1).round(2)
)

df_sin_inicio_plantilla['tiempo_respuesta_minutos'] = (df_sin_inicio_plantilla['tiempo_respuesta_segundos'] / 60).round(2)
df_sin_inicio_plantilla['tiempo_respuesta_horas'] = (df_sin_inicio_plantilla['tiempo_respuesta_minutos'] / 60).round(2)

promedio_sin_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].mean()


# df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe()

# infiltrado = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] == 0.100000]
# infiltrado

df_tiempo_sin_inicio_plantilla = df_sin_inicio_plantilla[['id', 'created_at', 'first_reply_created_at', 'tiempo_respuesta_minutos']]
df_tiempo_sin_inicio_plantilla = df_tiempo_sin_inicio_plantilla.rename(columns={'id':'conversation_id'})
promedio_sin_plantilla

np.float64(21.486550542547114)

## Promedio primera respuesta conversaciones iniciadas con plantilla

In [32]:
ids_conv_iniciadas_plantilla = df.loc[df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False),'id']

df_messages_conv_ini_plantilla = df_all_messages[df_all_messages['conversation_id'].isin(ids_conv_iniciadas_plantilla)].copy()
df_messages_conv_ini_plantilla = df_messages_conv_ini_plantilla.sort_values(['conversation_id', 'created_at'])

primer_mensaje_contacto = df_messages_conv_ini_plantilla[
    (df_messages_conv_ini_plantilla['message_type'] == 0) & 
    (~df_messages_conv_ini_plantilla['content'].isin(['system_resolved', 'system_timeout']))].groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'created_at_type_0'})

df_merge_tiempo_primer_mensaje_contacto = df_messages_conv_ini_plantilla.merge(primer_mensaje_contacto, on='conversation_id', how='inner')

df_mensajes_agente = df_merge_tiempo_primer_mensaje_contacto[
    (df_merge_tiempo_primer_mensaje_contacto['message_type'] == 1) &
    (df_merge_tiempo_primer_mensaje_contacto['private'] != True) &
    (df_merge_tiempo_primer_mensaje_contacto['created_at'] > df_merge_tiempo_primer_mensaje_contacto['created_at_type_0'])
]

df_primera_respuesta = (df_mensajes_agente.sort_values(['conversation_id', 'created_at']).groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'first_reply_created_at'}))

df_first_messages = primer_mensaje_contacto.merge(df_primera_respuesta,on='conversation_id',how='left')
df_first_messages = df_first_messages.rename(columns={'created_at_type_0': 'created_at'})

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_localize('UTC')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_localize('UTC')

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_convert('America/Bogota')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia_plantilla =  df_first_messages['created_at'].dt.date == df_first_messages['first_reply_created_at'].dt.date
df_first_messages['tiempo_respuesta_minutos'] = np.where(
    mismo_dia_plantilla,
    (df_first_messages.apply(calcular_mismo_dia, axis=1) / 60).round(2),
    (df_first_messages.apply(calcular_dia_distinto, axis=1) / 60).round(2)
)

promedio_con_plantilla = df_first_messages['tiempo_respuesta_minutos'].mean() 

promedio_con_plantilla

np.float64(37.09647058823529)

# Promedio Tiempo primera respuesta

In [40]:

total_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].sum()
cantidad_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].count()

total_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].count()

promedio_total = ((total_inicio_plantilla + total_sin_inicio_plantilla) / (cantidad_inicio_plantilla + cantidad_sin_inicio_plantilla)).round(2)


df_respuesta_plantilla = pd.DataFrame({
    "tipo": [
        "con plantilla",
        "sin plantilla",
        "total"
    ],
    "promedio_minutos": [
        promedio_con_plantilla,
        promedio_sin_plantilla,
        promedio_total
    ]
})

df_tiempo_respuesta_unificados = pd.concat([df_tiempo_sin_inicio_plantilla, df_first_messages], ignore_index=True)


detalles = df_tiempo_respuesta_unificados['tiempo_respuesta_minutos'].describe().to_frame()

promedio_total
detalles


#Entregar el resumen en este total

       tiempo_respuesta_minutos
count               2023.000000
mean                  23.585363
std                   49.703298
min                    0.000000
25%                    2.155000
50%                    7.530000
75%                   23.105000
max                  553.670000

# Promedio primera respuesta por agente

In [35]:

first_message_contact = (
    df_messages[
        (df_messages['message_type'] == 0) & 
        (~df_messages['content'].isin(['system_resolved', 'system_timeout']))
    ]
    .sort_values('created_at')
    .groupby('conversation_id', as_index=False)
    .first()[['conversation_id', 'created_at']]
    .rename(columns={'created_at': 'created_at_type_0'})
)
df_merge_first_time_contact = df_messages.merge(first_message_contact, on='conversation_id', how='inner')


messages_agent = df_merge_first_time_contact[
    (df_merge_first_time_contact['message_type'] == 1) &
    (df_merge_first_time_contact['sender_id'] != 1) & 
    (df_merge_first_time_contact['sender_id'] != 11) & 
    (df_merge_first_time_contact['private'] != True) &
    (df_merge_first_time_contact['created_at'] > df_merge_first_time_contact['created_at_type_0'])
]


first_message_agent = (
    messages_agent.sort_values(['conversation_id', 'created_at'])
    .groupby('conversation_id', as_index=False)
    .first()[['conversation_id', 'created_at', 'sender_id']]
    .rename(columns={'created_at': 'first_reply_created_at'})
    )

df_merge_firsts = first_message_contact.merge(first_message_agent,on='conversation_id',how='left')

df_merge_firsts = df_merge_firsts.rename(columns={'created_at_type_0': 'created_at'})

df_merge_firsts['created_at'] = df_merge_firsts['created_at'].dt.tz_localize('UTC')
df_merge_firsts['first_reply_created_at'] = df_merge_firsts['first_reply_created_at'].dt.tz_localize('UTC')

df_merge_firsts['created_at'] = df_merge_firsts['created_at'].dt.tz_convert('America/Bogota')
df_merge_firsts['first_reply_created_at'] = df_merge_firsts['first_reply_created_at'].dt.tz_convert('America/Bogota')

same_day = df_merge_firsts['created_at'].dt.date == df_merge_firsts['first_reply_created_at'].dt.date
df_merge_firsts['tiempo_respuesta_minutos'] = np.where(
    same_day,
    (df_merge_firsts.apply(calcular_mismo_dia, axis=1) / 60).round(2),
    (df_merge_firsts.apply(calcular_dia_distinto, axis=1) / 60).round(2)
)
df_merge_firsts.head(20)

promedio_agente = df_merge_firsts.groupby('sender_id')['tiempo_respuesta_minutos'].mean().reset_index(name='promedio_min')

promedio_agente["sender_id"] = promedio_agente["sender_id"].map(agentes).fillna(promedio_agente["sender_id"])
promedio_agente
# infi = df_merge_firsts[df_merge_firsts['sender_id'] == 15]
# df_merge_firsts.head(30)
# infi

          sender_id  promedio_min
0  Andres echeverry     12.976289
1           Viviana     24.228208
2             Jenny     27.860521
3             Edwar     25.626897
4             Diana     17.873843

# Metrica #4. Tiempo Promedio de Respuesta

Mediana del tiempo entre mensajes usuario → agente durante conversaciones activas.

In [39]:
sentencia_messages_contact_user = "SELECT * FROM messages WHERE created_at >= '2025-11-01'"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])
df_messages_contact_user = df_messages_contact_user[df_messages_contact_user['conversation_id'].isin(ids_conversaciones_validas)]

df_messages_contact_user['prev_message_type'] = df_messages_contact_user.groupby('conversation_id')['message_type'].shift(1)

df_messages_contact_user['is_first_in_block'] = (
    (df_messages_contact_user['message_type'] == 0) &
    (df_messages_contact_user['prev_message_type'] != 0) 
)

mensajes_usuario = df_messages_contact_user[
    df_messages_contact_user['is_first_in_block']
][['conversation_id', 'created_at']].rename(columns={'created_at': 'inicio_bloque'})


mensajes_agente = df_messages_contact_user[
    df_messages_contact_user['message_type'] == 1
][['conversation_id', 'created_at']].rename(columns={'created_at': 'respuesta_agente'})

respuestas = mensajes_usuario.merge(mensajes_agente, on='conversation_id')
respuestas = respuestas[respuestas['respuesta_agente'] > respuestas['inicio_bloque']]
respuestas = (
    respuestas
    .sort_values('respuesta_agente')
    .groupby(['conversation_id', 'inicio_bloque'])
    .first()
    .reset_index()
)

respuestas = respuestas.rename(columns={
    'inicio_bloque': 'created_at',
    'respuesta_agente': 'next_created_at'
})
respuestas['created_at'] = pd.to_datetime(respuestas['created_at'])
respuestas['next_created_at'] = pd.to_datetime(respuestas['next_created_at'])

respuestas['created_at'] = respuestas['created_at'].dt.tz_localize('UTC').dt.tz_convert('America/Bogota')
respuestas['next_created_at'] = respuestas['next_created_at'].dt.tz_localize('UTC').dt.tz_convert('America/Bogota')

mismo_dia_respuestas = respuestas['created_at'].dt.date == respuestas['next_created_at'].dt.date

def medir_dia_distinto(row):
    created_at = row['created_at']

    next_created_at = row['next_created_at']

    inicio_laboral_created_at = created_at.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = created_at.replace(hour=17, minute=0, second=0, microsecond=0)

    inicio_laboral_next = next_created_at.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_next = next_created_at.replace(hour=17, minute=0, second=0, microsecond=0)
    
    if created_at.weekday() == 5:
        inicio_laboral_created_at = created_at.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = created_at.replace(hour=12, minute=0, second=0, microsecond=0)

    if next_created_at.weekday() == 5:
        inicio_laboral_next = next_created_at.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_next = next_created_at.replace(hour=12, minute=0, second=0, microsecond=0)

    segundos = 0
    if created_at >= inicio_laboral_created_at and created_at <= fin_laboral_created_at and created_at.weekday() != 6:
        segundos += (fin_laboral_created_at - created_at).total_seconds()
    
    if next_created_at >= inicio_laboral_next and next_created_at <= fin_laboral_next:
        segundos += (next_created_at - inicio_laboral_next).total_seconds()

    return max(segundos, 0)

def medir_mismo_dia(row):
    created_at = row['created_at']

    next_created_at = row['next_created_at']

    inicio_laboral_created_at = created_at.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = created_at.replace(hour=18, minute=0, second=0, microsecond=0)
    
    segundos = 0
    if created_at >= inicio_laboral_created_at and created_at <= fin_laboral_created_at:
        segundos += (next_created_at - created_at).total_seconds()
    else:
        segundos += (next_created_at - inicio_laboral_created_at).total_seconds()

    return max(segundos, 0)

respuestas['response_time_minutes'] = np.where(
    mismo_dia_respuestas,
    (respuestas.apply(medir_mismo_dia, axis=1) / 60).round(2),
    (respuestas.apply(medir_dia_distinto, axis=1) / 60).round(2)
)

duracion_conversacion = (
    respuestas
    .groupby('conversation_id')['response_time_minutes']
    .mean()
    .reset_index(name='duracion_total_minutos')
)

promedio_duracion_conversacion = (
    duracion_conversacion['duracion_total_minutos']
    .mean()
    .round(2)
)
duracion_conversacion.describe()

# 0	321	16.963333
# 1	322	1.763333
# 2	325	3.820000
# 3	327	3.300000
# 4	328	0.486667

# 1898	2749	8.020000
# 1899	2751	0.000000
# 1900	2752	54.670000
# 1901	2753	17.790000

# i = duracion_conversacion[duracion_conversacion['duracion_total_minutos'] ==744.750000]
# i

       conversation_id  duracion_total_minutos
count      2006.000000             2006.000000
mean       1558.256730               22.657056
std         707.404937               57.992876
min         319.000000                0.000000
25%         938.250000                3.790000
50%        1565.500000                8.907500
75%        2177.750000               21.660000
max        2754.000000             1004.110000

# Metrica #5. Conversión agendamiento (%)

## Porcentaje conversaciones iniciadas en agendamiento que se agendaron

In [131]:

df_iniciadas_agendamiento = df[
    df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

agendamiento_exitoso = df_iniciadas_agendamiento[df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

iniciada_agendamiento = df_iniciadas_agendamiento[~df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

porcentaje_exito_sobre_iniciadas = (len(agendamiento_exitoso) / len(df_iniciadas_agendamiento)) * 100
porcentaje_exito_sobre_iniciadas

49.42084942084942

# Porcentaje de conversaciones no iniciadas en agendamiento que se agendaron

In [132]:

df_no_iniciadas_agendamiento = df[
    ~df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

no_iniciadas_agendamiento_agendadas = df_no_iniciadas_agendamiento[df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

no_iniciadas_agendamiento_no_agendadas = df_no_iniciadas_agendamiento[~df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

len(no_iniciadas_agendamiento_no_agendadas)

porcentaje_exito_no_iniciadas = (len(no_iniciadas_agendamiento_agendadas) / len(df_no_iniciadas_agendamiento)) * 100
porcentaje_exito_no_iniciadas

27.064676616915424

# Porcentaje de conversaciones agendadas

In [133]:
agendamiento_exitoso = df[df['cached_label_list'].str.contains('agendamiento_exitoso')]

cant_agendadas = len(agendamiento_exitoso)

porcentaje_total_agendadas = (cant_agendadas / len(df))*100
porcentaje_total_agendadas


df_metricas_agendamiento = pd.DataFrame({
    "metrica": [
        "exito sobre iniciadas",
        "exito sobre no iniciadas",
        "total conversaciones agendadas"
    ],
    "valor": [
        porcentaje_exito_sobre_iniciadas,
        porcentaje_exito_no_iniciadas,
        porcentaje_total_agendadas
    ]
})

df_metricas_agendamiento

                          metrica      valor
0           exito sobre iniciadas  49.420849
1        exito sobre no iniciadas  27.064677
2  total conversaciones agendadas  34.668418

# Metrica #7. Índice de Eficiencia del Agente (AEI) [0–100] (Hacer mas adelante cuando se perfeccione la metrica de primera respuesta)

In [14]:
df = df.sort_values(['assignee_id'])
ids_contacts = df['contact_id'].unique()
df = df.sort_values(['contact_id'])
df.head()

,id,account_id,inbox_id,status,assignee_id,created_at,updated_at,contact_id,display_id,contact_last_seen_at,...,snoozed_until,custom_attributes,assignee_last_seen_at,first_reply_created_at,priority,sla_policy_id,waiting_since,cached_label_list,holiday,weekday
799,1148,1,1,1,1.0,2025-11-18 01:48:29.496242,2025-11-18 01:51:54.746621,19,1148,None,...,None,{},2025-11-18 01:51:54.863121,2025-11-18 01:48:29.506161,NaN,None,NaT,iniciada_con_plantilla,False,1
151,319,1,1,1,NaN,2025-11-04 11:52:18.199918,2025-11-04 13:35:50.483685,27,319,None,...,None,{},2025-11-04 13:35:50.556647,2025-11-04 13:04:54.330977,0.0,None,NaT,agendamiento,False,1
47,320,1,1,1,NaN,2025-11-04 11:59:56.551432,2025-11-04 14:38:09.174962,28,320,None,...,None,{},2025-11-04 14:38:09.253493,2025-11-04 12:55:35.840898,0.0,None,NaT,agendamiento,False,1
2018,2320,1,1,1,NaN,2025-11-26 14:18:03.168174,2025-11-26 14:32:19.450570,29,2320,None,...,None,{},2025-11-26 14:23:15.342369,2025-11-26 14:18:03.193668,NaN,None,NaT,iniciada_con_plantilla,False,2
19,321,1,1,1,NaN,2025-11-04 12:29:42.598828,2025-11-04 15:10:25.272329,29,321,None,...,None,{},2025-11-04 15:23:00.051161,2025-11-04 12:56:13.355787,0.0,None,NaT,,False,1

# Metrica 8

In [26]:
sentencia_sessions = "SELECT * FROM sessions WHERE created_at >= '2025-11-01' AND (bot_feedback IS NOT NULL OR agent_feedback IS NOT NULL)"
df_sessions = pd.read_sql(sentencia_sessions, engine2)
df_sessions = df_sessions[df_sessions['conv_id'].isin(ids_conversaciones_validas)]
df_sessions

bot = df_sessions['bot_feedback'].mean().round(1)


agent = df_sessions['agent_feedback'].mean().round(1)
agent

np.float64(4.6)

In [ ]:

plantilla = [
    '¡Hola! 👋Bienvenido/a al canal exclusivo de asignación de citas de IMÁGENES DIAGNOSTICAS S.A.', 
    'Le acabo de enviar los documentos correspondientes a su solicitud. Por favor, revíselos y cuéntenos si tiene alguna duda. ¿Podemos ayudarle en algo más?', 
    '¡Con gusto! Procederemos a cancelar su cita, por favor, envíanos los siguientes datos para gestionar mejor nuestra agenda y su solicitud.',
    'Recuerde que su lugar de atención es: Centro De Especialistas De Risaralda, Carrera 5 No 18-33,',
    'Para programar su cita, por favor indíquenos los siguientes datos:',
    'Lamentamos la demora en nuestra respuesta. Ayer enfrentamos una contingencia, pero ya estamos atendiendo su solicitud. ¡Gracias por su paciencia!',
    '¡Gracias por elegirnos! 💙 Esperamos poder atenderte nuevamente. Feliz día🌞 En caso de requerir algo adicional, escríbenos en cualquier momento. ¡Estamos para servirte! 😊',
    'Por la complejidad del procedimiento solicitado y su seguridad, requerimos que por favor, nos confirme los siguientes datos:', 
    '📌 Para la solicitud y agendamientos de citas a través del Hospital Universitario San Jorge',
    '📌 Para la solicitud y agendamientos de exámenes de Hemodinamia, agradecemos que por favor nos contacte a través del siguiente WhatsApp 3128345850.',
    'nuestros horarios de atención son de lunes a viernes de 7:00 a.m a 5:00 p.m sabados de 8:00 a.m a 12:00 pm domingos y festivos cerrado',
    'IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comunicación y el interés en nuestros servicios.',
    '⌛ "Agradecemos su paciencia. Actualmente estamos recibiendo un volumen de usuarios mayor al habitual, por lo que estamos atendiendo los mensajes por orden de llegada.',
    'Nos permitimos informar que, para la solicitud y consulta de sus resultados',
    '¡Con gusto! Procederemos a reprogramar su cita, por favor, envíanos los siguientes datos para gestionar mejor nuestra agenda y su solicitud.'     
]

df_messages_agent = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages_agent = df_messages_agent[
    ((df_messages_agent['created_at'].dt.weekday != 6) & (df_messages_agent['created_at'].dt.weekday != 5) & (df_messages_agent['created_at'].dt.hour >=12) & (df_messages_agent['created_at'].dt.hour <=22)) | (
        (df_messages_agent['created_at'].dt.weekday == 5) &
        (df_messages_agent['created_at'].dt.hour >= 13) &
        (df_messages_agent['created_at'].dt.hour <= 17)
    )
]

df_messages_agent = df_messages_agent[(df_messages_agent['sender_type'] == 'User') & (df_messages_agent['sender_id'] != 1)  & (df_messages_agent['sender_id'] != 11)]

df_messages_agent = df_messages_agent.sort_values(['conversation_id', 'created_at'])

ppm = 40        

df_messages_agent['cantidad_palabras'] = df_messages_agent['content'].fillna("").str.split().str.len()

df_messages_agent['tiempo_minutos_mensaje'] = (df_messages_agent['cantidad_palabras'] / ppm).round(2)

df_messages_agent['created_at'] = pd.to_datetime(df_messages_agent['created_at'])

df_messages_agent['content'] = df_messages_agent['content'].astype(str)

plantillas_escaped = [re.escape(p) for p in plantilla] 

patron = "|".join(plantillas_escaped)
df_messages_agent = df_messages_agent[~df_messages_agent['content'].str.contains(patron, na=False)]

cantidad_minutos_diarios = (
    df_messages_agent
    .groupby([
        df_messages_agent['created_at'].dt.date, 
        'sender_id'
    ])['tiempo_minutos_mensaje'].sum().reset_index(name="minutos")
)


cantidad_minutos_diarios["sender_id"] = cantidad_minutos_diarios["sender_id"].map(agentes).fillna(cantidad_minutos_diarios["sender_id"])
cantidad_minutos_diarios.head(20)
# df_prueba_agent = df_messages_agent[(df_messages_agent['sender_id'] == 11) & (df_messages_agent['created_at'].dt.day == 5)]

# suma = df_prueba_agent['tiempo_minutos_mensaje'].sum() 
# suma

    created_at         sender_id  minutos
0   2025-11-04  Andres echeverry     5.42
1   2025-11-04             Jenny     1.03
2   2025-11-05           Viviana     1.84
3   2025-11-05             Jenny    26.45
4   2025-11-05             Edwar     2.73
5   2025-11-06           Viviana    20.68
6   2025-11-06             Jenny     7.12
7   2025-11-06             Edwar    14.55
8   2025-11-07           Viviana    26.31
9   2025-11-07             Jenny     0.82
10  2025-11-07             Edwar    13.14
11  2025-11-08           Viviana     7.09
12  2025-11-10           Viviana    31.09
13  2025-11-10             Edwar    22.18
14  2025-11-11  Andres echeverry    10.13
15  2025-11-11           Viviana    24.35
16  2025-11-11             Jenny    24.07
17  2025-11-11             Diana     0.80
18  2025-11-12  Andres echeverry     0.77
19  2025-11-12           Viviana    21.00

# Metrica #9. Utilización de Capacidad (%)

In [ ]:
agentes_asis = df_messages_agent[df_messages_agent['created_at'].dt.day == 5]['sender_id'].unique()
agentes_asis

### Celula consultar datos

In [20]:
ids_caso_raro = [6175, 6877, 6214, 6057]
sentencia_messages_contact_user = "SELECT * FROM messages WHERE sender_id = 16"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine) 

df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_localize('UTC')
df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_convert('America/Bogota')

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])

df_messages_contact_user.head(90)



# Lista de agentes
# 6.0   -> Andres echeverry
# 9.0   -> Angel
# 10.0  -> Viviana
# 12.0  -> Jenny
# 13.0  -> Edwar
# 14.0	-> Natalia
# 15.0  -> Diana

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
2713,174566,None,1,2,261,1,2026-02-12 10:59:38.107591-05:00,2026-02-12 15:59:38.107591,False,0,None,0,None,User,16,None,{},None,{}
4616,198871,"FECHA Y HORA DE LA CITA:\t2026-03-05, 07:15 am...",1,2,261,1,2026-02-24 15:15:55.651411-05:00,2026-02-24 20:15:55.651411,False,0,None,0,None,User,16,None,{},"FECHA Y HORA DE LA CITA:\t2026-03-05, 07:15 am...",{}
4611,198872,* TENER AYUNO COMPLETO EL DIA DE LA CITA\n * 1...,1,2,261,1,2026-02-24 15:16:25.892181-05:00,2026-02-24 20:16:25.892181,False,0,None,0,None,User,16,None,{},* TENER AYUNO COMPLETO EL DIA DE LA CITA\n * 1...,{}
4617,198873,Recuerde que su lugar de atención es: Centro D...,1,2,261,1,2026-02-24 15:16:29.604650-05:00,2026-02-24 20:16:29.604650,False,0,None,0,None,User,16,None,{},Recuerde que su lugar de atención es: Centro D...,{}
3143,203362,https://oficinavirtualmp.coomeva.com.co/presta...,1,2,261,1,2026-02-26 10:11:25.107053-05:00,2026-02-26 15:11:25.107053,False,0,None,0,None,User,16,None,{},https://oficinavirtualmp.coomeva.com.co/presta...,{}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,123595,¡Gracias por elegirnos! 💙 Esperamos poder aten...,1,1,7137,1,2026-01-20 13:52:01.052438-05:00,2026-01-20 18:52:01.052438,False,0,None,0,None,User,16,None,{},¡Gracias por elegirnos! 💙 Esperamos poder aten...,{}
263,122723,\n💙 Esperamos poder atenderte nuevamente. Feli...,1,1,7141,1,2026-01-20 10:12:23.123910-05:00,2026-01-20 15:12:23.123910,False,0,None,0,None,User,16,None,{},\n💙 Esperamos poder atenderte nuevamente. Feli...,{}
262,122778,"Para programar su cita, por favor indíquenos l...",1,1,7142,1,2026-01-20 10:28:02.970154-05:00,2026-01-20 15:28:02.970154,False,0,None,0,None,User,16,None,{},"Para programar su cita, por favor indíquenos l...",{}
270,122922,"He recibido su información, Señor Luis Fernand...",1,1,7142,1,2026-01-20 10:50:25.908975-05:00,2026-01-20 15:50:25.908975,False,0,None,0,None,User,16,None,{},"He recibido su información, Señor Luis Fernand...",{}
274,122941,CONFIRMAR CON EL MÉDICO\n \t \nFECHA Y HORA DE...,1,1,7142,1,2026-01-20 11:00:42.747567-05:00,2026-01-20 16:00:42.747567,False,0,None,0,None,User,16,None,{},CONFIRMAR CON EL MÉDICO\n \t \nFECHA Y HORA DE...,{}