In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import holidays
import matplotlib.pyplot as plt
engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")

# Metrica #1. Promedio Diario de Conversaciones

In [144]:
sentencia = "SELECT * FROM conversations WHERE created_at >= '2025-11-01'"

year_rp = 2026
month_rp = 1

co_holidays = holidays.Colombia(years=year_rp)
co_holidays_dt = pd.to_datetime(list(co_holidays))

df = pd.read_sql(sentencia, engine)
df['created_at'] = pd.to_datetime(df['created_at'])

df = df[(df['created_at'].dt.year == year_rp) & (df['created_at'].dt.month == month_rp)]
df = df.sort_values(['id', 'created_at'])

df['holiday'] = df['created_at'].dt.normalize().isin(co_holidays_dt)


contactos = pd.read_sql("SELECT * FROM contacts WHERE name ~ '[A-Za-z]'", engine)
ids_ignorar_contactos = contactos['id'].unique()
ids_ignorar_contactos = ids_ignorar_contactos.tolist()

#total cantidad datos sin filtrar
cantidad_datos_sin_filtrar = len(df)


ids_conversaciones_ignorar = df.loc[df['contact_id'].isin(ids_ignorar_contactos), 'id']


ids_sin_first_reply_created_at = df.loc[df['first_reply_created_at'].isna(), 'id']
ids_conversaciones_ignorar = pd.concat([ids_conversaciones_ignorar, ids_sin_first_reply_created_at]).unique()

cantidad_conversaciones_ignoradas_contactos = df['id'].isin(ids_conversaciones_ignorar).sum()

df = df[~df['id'].isin(ids_conversaciones_ignorar)]

#Serie con datos de registros ignorados por contactos
cantidad_conversaciones_festivos = df[df['holiday']]
#--

df = df[~df['holiday']]
cantidad_datos_filtrados = len(df)
df['weekday'] = df['created_at'].dt.weekday
promedios_24_h = (
    df.groupby([df['weekday'], df['created_at'].dt.to_period('D')]).size().groupby(level=0).mean().round(2)
)

# df_lunes = df[(df['created_at'].dt.weekday == 0)]
# promedio_lunes = df_lunes.groupby(df_lunes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_martes = df[(df['created_at'].dt.weekday == 1)]
# promedio_martes = df_martes.groupby(df_martes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_miercoles = df[(df['created_at'].dt.weekday == 2)]
# promedio_miercoles = df_miercoles.groupby(df_miercoles['created_at'].dt.to_period('D')).size().mean().round(2)

# df_jueves = df[(df['created_at'].dt.weekday == 3)]
# promedio_jueves = df_jueves.groupby(df_jueves['created_at'].dt.to_period('D')).size().mean().round(2)

# df_viernes = df[(df['created_at'].dt.weekday == 4)]
# promedio_viernes = df_viernes.groupby(df_viernes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_sabado = df[(df['created_at'].dt.weekday == 5)]
# promedio_sabado = df_sabado.groupby(df_sabado['created_at'].dt.to_period('D')).size().mean().round(2)

# df_domingo = df[(df['created_at'].dt.weekday == 6)]
# promedio_domingo = df_domingo.groupby(df_domingo['created_at'].dt.to_period('D')).size().mean().round(2)


print(f"Cantidad datos antes de ignorar: {cantidad_datos_sin_filtrar}")
print(f"Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: {cantidad_conversaciones_ignoradas_contactos}")
print(f"Cantidad conversaciones ignoradas por festivos: {len(cantidad_conversaciones_festivos)}")

print(f"Cantidad datos despues de ignorar: {cantidad_datos_filtrados}\n")

print(f"Anio: {year_rp} - Mes: {month_rp}")
print(f"Promedios conversaciones del mes 24h: \n")
print(f"Lunes: {promedios_24_h[0]}")
print(f"Martes: {promedios_24_h[1]}")
print(f"Miercoles: {promedios_24_h[2]}")
print(f"Jueves: {promedios_24_h[3]}")
print(f"Viernes: {promedios_24_h[4]}")
print(f"Sabado: {promedios_24_h[5]}")
print(f"Domingo: {promedios_24_h[6]} \n")

print("Promedios hora laboral")

# agregas columna con weekday
df_habiles = df.copy()
df_habiles['weekday'] = df_habiles['created_at'].dt.weekday

df_habiles = df_habiles[
    ((df_habiles['weekday'] != 6) & (df_habiles['weekday'] != 5) & (df_habiles['created_at'].dt.hour >=12) & (df_habiles['created_at'].dt.hour <=22)) | (
        (df_habiles['weekday'] == 5) &
        (df_habiles['created_at'].dt.hour >= 13) &
        (df_habiles['created_at'].dt.hour <= 17)
    )
]

# agrupas por weekday y día
promedios = (
    df_habiles.groupby([df_habiles['weekday'], df_habiles['created_at'].dt.to_period('D')])
    .size()
    .groupby(level=0)  # promedio por weekday
    .mean()
    .round(2)
)

ids_conversaciones_validas = df['id'].unique()
promedios

Cantidad datos antes de ignorar: 1671
Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: 133
Cantidad conversaciones ignoradas por festivos: 15
Cantidad datos despues de ignorar: 1523

Anio: 2026 - Mes: 1
Promedios conversaciones del mes 24h:

Lunes: 145.5
Martes: 158.0
Miercoles: 138.0
Jueves: 120.0
Viernes: 101.33
Sabado: 25.0
Domingo: 7.0

Promedios hora laboral

weekday
0    142.00
1    152.00
2    132.00
3    114.00
4     98.67
5     20.67
dtype: float64

# Metrica  #2. Promedio de mensajes por hora

In [76]:


sentencia_messages = "SELECT * FROM messages WHERE created_at >= '2025-11-01'" 

df_all_messages = pd.read_sql(sentencia_messages, engine)

df_messages = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages = df_messages.sort_values(['conversation_id', 'created_at'])

df_messages = df_messages[(df_messages['sender_type'].notna()) & (df_messages['sender_type'] != 'User')]

df_messages['weekday'] = df_messages['created_at'].dt.weekday

promedios_por_hora_24h = (df_messages.groupby([df_messages['weekday'], df_messages['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))

print(f"Total mensajes de contactos en el mes: {len(df_messages)}\n")
print(f"Promedio mensajes de contactos en las 24h:")
print(f"Lunes: {promedios_por_hora_24h[0]}")
print(f"Martes: {promedios_por_hora_24h[1]}")
print(f"Miercoles: {promedios_por_hora_24h[2]}")
print(f"Jueves: {promedios_por_hora_24h[3]}")
print(f"Viernes: {promedios_por_hora_24h[4]}")
print(f"Sabado: {promedios_por_hora_24h[5]}")
print(f"Sabado: {promedios_por_hora_24h[6]} \n")


df_habiles_messag = df_messages[
    ((df_messages['weekday'] != 6) & (df_messages['weekday'] != 5) & (df_messages['created_at'].dt.hour >=12) & (df_messages['created_at'].dt.hour <=22)) | (
        (df_messages['weekday'] == 5) &
        (df_messages['created_at'].dt.hour >= 13) &
        (df_messages['created_at'].dt.hour <= 17)
    )
]
promedios_por_hora = (df_habiles_messag.groupby([df_habiles_messag['weekday'], df_habiles_messag['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))
promedios_por_hora

print(f"Promedio mensajes de contactos en horario laboral:")
print(f"Lunes:{promedios_por_hora[0]}")
print(f"Martes: {promedios_por_hora[1]}")
print(f"Miercoles: {promedios_por_hora[2]}")
print(f"Jueves: {promedios_por_hora[3]}")
print(f"Viernes: {promedios_por_hora[4]}")
print(f"Sabado: {promedios_por_hora[5]}")

Total mensajes de contactos en el mes: 14461

Promedio mensajes de contactos en las 24h:
Lunes: 49.61
Martes: 42.65
Miercoles: 32.81
Jueves: 43.15
Viernes: 34.42
Sabado: 15.85
Sabado: 2.22

Promedio mensajes de contactos en horario laboral:
Lunes:68.5
Martes: 62.38
Miercoles: 49.2
Jueves: 68.15
Viernes: 50.23
Sabado: 30.32

## Hacer el promedio de primera respuesta solo de conversaciones que se crearon dentro del horario laboral

In [ ]:
# Promedio de primera respuesta de conversaciones que se iniciaron en cualquier hora y se calcula dependiendo de la la hora de la primera respuesta
# Por ejemplo: primer mensaje de usuario: miercoles 7pm; primera respuesta: 8:30am. Tiempo de primera respuesta = 90min


# Promedio de primera respuesta de conversaciones que se iniciaron solo en horario laboral, ignorando domingos, festivos y conversaciones que se crearon por fuera del horario laboral
# En este caso el ejemplo de arriba no aplica aqui porque la conversacion no se debe tomar en cuenta

# Metrica #3 Tiempo de Primera Respuesta

In [135]:
df_sin_inicio_plantilla = df[~df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False)].copy()

#6501, 6807
df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_localize('UTC')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_localize('UTC')

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_convert('America/Bogota')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia = df_sin_inicio_plantilla['created_at'].dt.date == df_sin_inicio_plantilla['first_reply_created_at'].dt.date

def calcular_dia_distinto(row):
    inicio = row['created_at']
    fin = row['first_reply_created_at']

    segundos = 0

    inicio_laboral_create_at = inicio.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    inicio_laboral_first_reply = fin.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_first_reply = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        inicio_laboral_create_at = inicio.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
      
    if row['first_reply_created_at'].weekday() == 5:
        inicio_laboral_first_reply = fin.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_first_reply = fin.replace(hour=12, minute=0, second=0, microsecond=0)
        

    if inicio >= inicio_laboral_create_at and inicio < fin_laboral_created_at and row['created_at'].weekday() != 6:
        segundos +=(fin_laboral_created_at-inicio).total_seconds()
    

    if fin > inicio_laboral_first_reply:
        segundos +=(fin - inicio_laboral_first_reply).total_seconds()
    
    
    return segundos

def calcular_mismo_dia(row):
    inicio = row['created_at']
    fin = row['first_reply_created_at']

    segundos = 0

    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)
    inicio_laboral = fin.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        fin_laboral = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
        inicio_laboral = fin.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral and inicio < fin_laboral :
        segundos +=(fin-inicio).total_seconds()
    
    if inicio < inicio_laboral and fin <= fin_laboral:
        segundos +=(fin-inicio_laboral).total_seconds()
    
    return max(segundos, 0)
    
    
df_sin_inicio_plantilla['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    df_sin_inicio_plantilla.apply(calcular_mismo_dia, axis=1).round(2),
    df_sin_inicio_plantilla.apply(calcular_dia_distinto, axis=1).round(2)
)

df_sin_inicio_plantilla['tiempo_respuesta_minutos'] = (df_sin_inicio_plantilla['tiempo_respuesta_segundos'] / 60).round(2)
df_sin_inicio_plantilla['tiempo_respuesta_horas'] = (df_sin_inicio_plantilla['tiempo_respuesta_minutos'] / 60).round(2)

promedio_tiempo_respuesta_min = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].mean()
promedio_tiempo_respuesta_min


# print(df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe())
# v = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] ==  278.630000]
# v
# mitad = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] > 40]
# mitad.head(30)

print(df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe())
infiltrado = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] == 177.790000]
infiltrado

infiltrados = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] >= 240]
infiltrados

count    1967.000000
mean       27.898663
std        27.254554
min         0.000000
25%         8.210000
50%        19.500000
75%        40.525000
max       243.000000
Name: tiempo_respuesta_minutos, dtype: float64

,id,account_id,inbox_id,status,assignee_id,created_at,updated_at,contact_id,display_id,contact_last_seen_at,...,first_reply_created_at,priority,sla_policy_id,waiting_since,cached_label_list,holiday,weekday,tiempo_respuesta_segundos,tiempo_respuesta_minutos,tiempo_respuesta_horas
4048,4423,1,1,1,12.0,2025-12-17 11:35:10.548320-05:00,2025-12-22 14:50:46.718907,2528,4423,None,...,2025-12-17 15:38:10.474266-05:00,0.0,None,NaT,,False,2,14579.93,243.0,4.05

## Promedio primera respuesta conversaciones iniciadas con plantilla

In [88]:
# ids_caso_raro = [6175, 6877, 6214, 6057]
ids_conv_iniciadas_plantilla = df.loc[df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False),'id']

#ids_conv_iniciadas_plantilla = ids_conv_iniciadas_plantilla[~ids_conv_iniciadas_plantilla.isin(ids_caso_raro)]

df_messages_conv_ini_plantilla = df_all_messages[df_all_messages['conversation_id'].isin(ids_conv_iniciadas_plantilla)].copy()
df_messages_conv_ini_plantilla = df_messages_conv_ini_plantilla.sort_values(['conversation_id', 'created_at'])

primer_mensaje_contacto = df_messages_conv_ini_plantilla[(df_messages_conv_ini_plantilla['message_type'] == 0) & (~df_messages_conv_ini_plantilla['content'].isin(['system_resolved', 'system_timeout']))].groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'created_at_type_0'})

df_merge_tiempo_primer_mensaje_contacto = df_messages_conv_ini_plantilla.merge(primer_mensaje_contacto, on='conversation_id', how='inner')

df_mensajes_agente = df_merge_tiempo_primer_mensaje_contacto[
    (df_merge_tiempo_primer_mensaje_contacto['message_type'] == 1) &
    (df_merge_tiempo_primer_mensaje_contacto['private'] != True) &
    (df_merge_tiempo_primer_mensaje_contacto['created_at'] > df_merge_tiempo_primer_mensaje_contacto['created_at_type_0'])
]

df_primera_respuesta = (df_mensajes_agente.sort_values(['conversation_id', 'created_at']).groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'first_reply_created_at'})
)
df_first_messages = primer_mensaje_contacto.merge(df_primera_respuesta,on='conversation_id',how='left')
df_first_messages = df_first_messages.rename(columns={'created_at_type_0': 'created_at'})

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_localize('UTC')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_localize('UTC')

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_convert('America/Bogota')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia_plantilla =  df_first_messages['created_at'].dt.date == df_first_messages['first_reply_created_at'].dt.date
df_first_messages['tiempo_respuesta_minutos'] = np.where(
    mismo_dia_plantilla,
    (df_first_messages.apply(calcular_mismo_dia, axis=1) / 60).round(2),
    (df_first_messages.apply(calcular_dia_distinto, axis=1) / 60).round(2)
)

promedio = df_first_messages['tiempo_respuesta_minutos'].mean() 
promedio

#v = df_first_messages[df_first_messages['tiempo_respuesta_minutos'] ==  197.010000]

total_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].sum()
cantidad_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].count()

total_inicio_plantilla
cantidad_inicio_plantilla

total_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].count()

promedio_total = ((total_inicio_plantilla + total_sin_inicio_plantilla) / (cantidad_inicio_plantilla + cantidad_sin_inicio_plantilla)).round(2)
promedio_total

infiltrado = df_first_messages[df_first_messages['conversation_id'] == 6057]
infiltrado


# df_first_messages

,conversation_id,created_at,first_reply_created_at,tiempo_respuesta_minutos
69,6057,2026-01-08 16:46:34.170163-05:00,2026-01-09 07:24:28.188657-05:00,37.9

# Promedio primera respuesta conversaciones iniciadas solo en horario laboral

In [152]:
df_filtrado = df_sin_inicio_plantilla[
    (
        df_sin_inicio_plantilla['created_at'].dt.weekday.between(0, 4) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_sin_inicio_plantilla['created_at'].dt.weekday == 5) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(8, 11)
    )
]

df_filtrado
total_minutos_df_filtrado = df_filtrado['tiempo_respuesta_minutos'].sum()
cantidad_conversaciones_df_filtrado = df_filtrado['tiempo_respuesta_minutos'].count()

p = total_minutos_df_filtrado / cantidad_conversaciones_df_filtrado
promedio_laboral = df_filtrado['tiempo_respuesta_minutos'].mean()



df_filtrado2 = df_first_messages[
     (
        df_first_messages['created_at'].dt.weekday.between(0, 4) &
        df_first_messages['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_first_messages['created_at'].dt.weekday == 5) &
        df_first_messages['created_at'].dt.hour.between(8, 11)
    )
]
total_minutos_df_filtrado2 = df_filtrado2['tiempo_respuesta_minutos'].sum()
promedio_laboral2 = df_filtrado2['tiempo_respuesta_minutos'].mean()
df_filtrado2.shape
promedio_laboral2

np.float64(33.007734806629834)

# Metrica #4. Tiempo Promedio de Respuesta

Mediana del tiempo entre mensajes usuario → agente durante conversaciones activas.

In [94]:
sentencia_messages_contact_user = "SELECT * FROM messages WHERE created_at >= '2025-11-01'"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])
df_messages_contact_user = df_messages_contact_user[df_messages_contact_user['conversation_id'].isin(ids_conversaciones_validas)]

df_messages_contact_user['next_message_type'] = df_messages_contact_user.groupby('conversation_id')['message_type'].shift(-1)
df_messages_contact_user['next_created_at'] = df_messages_contact_user.groupby('conversation_id')['created_at'].shift(-1)

respuestas = df_messages_contact_user[
    (df_messages_contact_user['message_type'] == 0) &
    (df_messages_contact_user['next_message_type'] == 1)
].copy()

respuestas['response_time_minutes'] = ((respuestas['next_created_at'] - respuestas['created_at']).dt.total_seconds() / 60).round(2)

promedio_por_conversacion = (respuestas.groupby('conversation_id')['response_time_minutes'].mean()).round(2) 

promedio_por_conversacion
# respuestas

# infiltrado = respuestas[respuestas['conversation_id'] == 6143]
# v = respuestas['response_time_minutes'].describe()
# v
# infiltrado

conversation_id
5385    262.66
5386    269.41
5388      7.30
5389     20.13
5391     12.81
         ...
7035     31.07
7036      1.62
7037      0.34
7039      1.76
7041      1.96
Name: response_time_minutes, Length: 1426, dtype: float64

# Metrica #5. Conversión agendamiento (%)

In [ ]:
df_iniciadas_agendamiento = df[
    df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

agendamiento_exitoso = df_iniciadas_agendamiento[df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

iniciada_agendamiento = df_iniciadas_agendamiento[df_iniciadas_agendamiento['cached_label_list'] == 'agendamiento']

len(iniciada_agendamiento)
len(agendamiento_exitoso)
# 518 256

porcentaje_agendamiento_exitoso = (len(agendamiento_exitoso) / len(df_iniciadas_agendamiento)) * 100

porcentaje_agendamiento_no_exitoso = (len(iniciada_agendamiento) / len(df_iniciadas_agendamiento)) * 100


df_no_iniciadas_agendamiento = df[
    ~df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

no_iniciadas_agendamiento_agendadas = df_no_iniciadas_agendamiento[df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

no_iniciadas_agendamiento_no_agendadas = df_no_iniciadas_agendamiento[~df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

len(no_iniciadas_agendamiento_no_agendadas)

porcentaje_no_iniciadas_agendamiento_agendadas = (len(no_iniciadas_agendamiento_agendadas) / len(df_no_iniciadas_agendamiento)) * 100
print(porcentaje_agendamiento_exitoso)
print(porcentaje_no_iniciadas_agendamiento_agendadas)

49.42084942084942
27.064676616915424

(518, 27)

# Metrica #7. Índice de Eficiencia del Agente (AEI) [0–100]

In [153]:

df = df.sort_values(['assignee_id'])
ids_contacts = df['contact_id'].unique()
df = df.sort_values(['contact_id'])
df.head()

,id,account_id,inbox_id,status,assignee_id,created_at,updated_at,contact_id,display_id,contact_last_seen_at,...,snoozed_until,custom_attributes,assignee_last_seen_at,first_reply_created_at,priority,sla_policy_id,waiting_since,cached_label_list,holiday,weekday
6433,6501,1,1,1,12.0,2026-01-14 16:18:05.047403,2026-01-15 15:25:57.149538,33,6501,None,...,None,{},2026-01-15 15:25:57.218006,2026-01-14 20:56:42.601575,0.0,None,NaT,agendamiento,False,2
6208,6750,1,1,1,10.0,2026-01-16 15:56:15.713215,2026-01-16 16:21:45.774128,40,6750,None,...,None,{},2026-01-16 16:21:45.889305,2026-01-16 16:09:42.808488,0.0,None,NaT,agendamiento_exitoso,False,4
5388,5684,1,1,1,NaN,2026-01-06 14:11:21.209997,2026-01-06 17:25:08.388797,44,5684,None,...,None,{},NaT,2026-01-06 14:46:39.067066,0.0,None,NaT,serivicios_y_tarifas,False,1
5693,5979,1,1,1,12.0,2026-01-08 14:10:25.871172,2026-01-09 16:06:52.381127,57,5979,None,...,None,{},2026-01-09 16:06:52.454653,2026-01-08 14:52:37.566568,0.0,None,NaT,"agendamiento, agendamiento_exitoso",False,3
6207,6638,1,1,1,NaN,2026-01-15 16:16:51.206016,2026-01-15 17:51:11.918507,66,6638,None,...,None,{},NaT,2026-01-15 17:05:19.720650,0.0,None,NaT,,False,3

# Metrica #9. Utilización de Capacidad (%)

In [ ]:
df_messages_agent = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages_agent = df_messages_agent[(df_messages_agent['sender_type'] == 'User') & (df_messages_agent['sender_id'] != 1)]
df_messages_agent = df_messages_agent.sort_values(['conversation_id', 'created_at','sender_id'])
#tiempo estandar de escritura de un mensaje 40 PPM (palabras por minuto)
ppm = 40

df_messages_agent['cantidad_palabras'] = df_messages_agent['content'].fillna("").str.split().str.len()
df_messages_agent['tiempo_minutos_mensaje'] = (df_messages_agent['cantidad_palabras'] / ppm) * 60 
df_messages_agent.head(20)

df_messages_agent

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,...,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment,cantidad_palabras,tiempo_minutos_mensaje
85156,91783,¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,1,1,5385,1,2026-01-02 12:22:49.418219,2026-01-02 12:22:49.418219,False,0,...,0,None,User,10.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,{},22,33.0
80681,91784,*¡Con gusto!*\r\n\r\nEl examen tiene un valor ...,1,1,5385,1,2026-01-02 12:23:01.895567,2026-01-02 12:23:01.895567,False,0,...,0,None,User,10.0,None,{},*¡Con gusto!*\r\n\r\nEl examen tiene un valor ...,{},23,34.5
87292,92187,La disponibilidad para la tomografía se puede...,1,1,5385,1,2026-01-02 14:09:24.308731,2026-01-02 14:09:24.308731,False,0,...,0,None,User,10.0,None,{},La disponibilidad para la tomografía se puede...,{},13,19.5
87647,92415,*¿Agendamos la cita?*,1,1,5385,1,2026-01-02 15:22:32.657356,2026-01-02 15:22:32.657356,False,0,...,0,None,User,12.0,None,{},*¿Agendamos la cita?*,{},3,4.5
87934,92545,quedamos atentos,1,1,5385,1,2026-01-02 16:14:41.865329,2026-01-02 16:14:41.865329,False,0,...,0,None,User,6.0,None,{},quedamos atentos,{},2,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115253,120426,CONSULTA TUS IMAGENES E INFORMES DESDE NUESTRA...,1,1,7039,1,2026-01-19 18:54:45.598826,2026-01-19 18:54:45.598826,False,0,...,0,None,User,13.0,None,{},CONSULTA TUS IMAGENES E INFORMES DESDE NUESTRA...,{},55,82.5
115256,120447,"He enviado su solicitud al área encargada, tal...",1,1,7039,1,2026-01-19 18:58:07.126453,2026-01-19 18:58:07.126453,False,0,...,0,None,User,13.0,None,{},"He enviado su solicitud al área encargada, tal...",{},40,60.0
115273,120453,💙 Esperamos poder atenderte nuevamente. Feliz ...,1,1,7039,1,2026-01-19 18:59:34.814608,2026-01-19 18:59:34.814608,False,0,...,0,None,User,13.0,None,{},💙 Esperamos poder atenderte nuevamente. Feliz ...,{},21,31.5
115335,120452,¿Cuenta usted con una orden médica para determ...,1,1,7041,1,2026-01-19 18:59:12.385512,2026-01-19 18:59:12.385512,False,0,...,0,None,User,13.0,None,{},¿Cuenta usted con una orden médica para determ...,{},16,24.0
115347,120522,#plantilla_inicial SEGUIMIENTO_SOLICITUD {Jenn...,1,1,7047,1,2026-01-19 19:08:44.901972,2026-01-19 19:08:44.901972,False,0,...,0,None,User,12.0,None,{},#plantilla_inicial SEGUIMIENTO_SOLICITUD {Jenn...,{},4,6.0

### Celula consultar datos

In [137]:
ids_caso_raro = [6175, 6877, 6214, 6057]
sentencia_messages_contact_user = "SELECT * FROM messages WHERE conversation_id=4423"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_localize('UTC')
df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_convert('America/Bogota')

df_messages_contact_user = df_messages_contact_user.sort_values(['created_at'])

df_messages_contact_user.head(60)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
0,75018,Asignado a hospital por Sistema,1,1,4423,2,2025-12-17 11:35:10.571076-05:00,2025-12-17 16:35:10.571076,False,0,None,0,None,None,NaN,None,{},Asignado a hospital por Sistema,{}
1,75019,Sistema estableció la prioridad a low,1,1,4423,2,2025-12-17 11:35:10.602478-05:00,2025-12-17 16:35:10.602478,False,0,None,0,None,None,NaN,None,{},Sistema estableció la prioridad a low,{}
2,75020,Estoy pendiente del ajendamiento mil gracias,1,1,4423,0,2025-12-17 11:35:10.604205-05:00,2025-12-17 16:35:10.604205,False,0,None,0,None,Contact,2528.0,None,{},Estoy pendiente del ajendamiento mil gracias,{}
4,75677,¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,1,1,4423,1,2025-12-17 15:38:10.474266-05:00,2025-12-17 20:38:10.474266,False,0,None,0,None,User,12.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,{}
3,75678,Le ofrecemos una disculpa estamos en un proces...,1,1,4423,1,2025-12-17 15:39:20.393990-05:00,2025-12-17 20:39:20.393990,False,0,None,0,None,User,12.0,None,{},Le ofrecemos una disculpa estamos en un proces...,{}
5,76851,Esta conversacion ha sido cerrada por el siste...,1,1,4423,1,2025-12-18 11:31:00.058755-05:00,2025-12-18 16:31:00.058755,True,0,None,0,None,User,1.0,None,{},Esta conversacion ha sido cerrada por el siste...,{}
6,79024,[@Sistema](mention://user/1/Sistema),1,1,4423,1,2025-12-19 12:44:04.403688-05:00,2025-12-19 17:44:04.403688,True,0,None,0,None,User,10.0,None,{},[@Sistema](mention://user/1/Sistema),{}
7,79813,Jenny auto-asignado a esta conversación,1,1,4423,2,2025-12-20 09:07:09.023891-05:00,2025-12-20 14:07:09.023891,False,0,None,0,None,None,NaN,None,{},Jenny auto-asignado a esta conversación,{}
9,81180,La conversación fue marcada por Jenny,1,1,4423,2,2025-12-22 09:50:46.671912-05:00,2025-12-22 14:50:46.671912,False,0,None,0,None,None,NaN,None,{},La conversación fue marcada por Jenny,{}
8,81181,ERROR: Esta conversacion ya estaba cerrada.,1,1,4423,1,2025-12-22 09:50:46.717943-05:00,2025-12-22 14:50:46.717943,True,0,None,0,None,User,1.0,None,{},ERROR: Esta conversacion ya estaba cerrada.,{}