In [ ]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import holidays
import matplotlib.pyplot as plt
engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")

# Metrica #1. Promedio Diario de Conversaciones

In [ ]:
sentencia = "SELECT * FROM conversations WHERE created_at >= '2025-11-01'"

year_rp = 2025
month_rp = 11

co_holidays = holidays.Colombia(years=year_rp)
co_holidays_dt = pd.to_datetime(list(co_holidays))

df = pd.read_sql(sentencia, engine)
df['created_at'] = pd.to_datetime(df['created_at'])

df = df[(df['created_at'].dt.year == year_rp) & (df['created_at'].dt.month == month_rp)]
df = df.sort_values(['id', 'created_at'])

df['holiday'] = df['created_at'].dt.normalize().isin(co_holidays_dt)


contactos = pd.read_sql("SELECT * FROM contacts WHERE name ~ '[A-Za-z]'", engine)
ids_ignorar_contactos = contactos['id'].unique()
ids_ignorar_contactos = ids_ignorar_contactos.tolist()

#total cantidad datos sin filtrar
cantidad_datos_sin_filtrar = len(df)


ids_conversaciones_ignorar = df.loc[df['contact_id'].isin(ids_ignorar_contactos), 'id']


ids_sin_first_reply_created_at = df.loc[df['first_reply_created_at'].isna(), 'id']
ids_conversaciones_ignorar = pd.concat([ids_conversaciones_ignorar, ids_sin_first_reply_created_at]).unique()

cantidad_conversaciones_ignoradas_contactos = df['id'].isin(ids_conversaciones_ignorar).sum()

df = df[~df['id'].isin(ids_conversaciones_ignorar)]

#Serie con datos de registros ignorados por contactos
cantidad_conversaciones_festivos = df[df['holiday']]
#--

df = df[~df['holiday']]
cantidad_datos_filtrados = len(df)
df['weekday'] = df['created_at'].dt.weekday
promedios_24_h = (
    df.groupby([df['weekday'], df['created_at'].dt.to_period('D')]).size().groupby(level=0).mean().round(2)
)

# df_lunes = df[(df['created_at'].dt.weekday == 0)]
# promedio_lunes = df_lunes.groupby(df_lunes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_martes = df[(df['created_at'].dt.weekday == 1)]
# promedio_martes = df_martes.groupby(df_martes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_miercoles = df[(df['created_at'].dt.weekday == 2)]
# promedio_miercoles = df_miercoles.groupby(df_miercoles['created_at'].dt.to_period('D')).size().mean().round(2)

# df_jueves = df[(df['created_at'].dt.weekday == 3)]
# promedio_jueves = df_jueves.groupby(df_jueves['created_at'].dt.to_period('D')).size().mean().round(2)

# df_viernes = df[(df['created_at'].dt.weekday == 4)]
# promedio_viernes = df_viernes.groupby(df_viernes['created_at'].dt.to_period('D')).size().mean().round(2)

# df_sabado = df[(df['created_at'].dt.weekday == 5)]
# promedio_sabado = df_sabado.groupby(df_sabado['created_at'].dt.to_period('D')).size().mean().round(2)

# df_domingo = df[(df['created_at'].dt.weekday == 6)]
# promedio_domingo = df_domingo.groupby(df_domingo['created_at'].dt.to_period('D')).size().mean().round(2)


print(f"Cantidad datos antes de ignorar: {cantidad_datos_sin_filtrar}")
print(f"Cantidad conversaciones ignoradas por contactos y conversaciones sin tiempo de primera respuesta: {cantidad_conversaciones_ignoradas_contactos}")
print(f"Cantidad conversaciones ignoradas por festivos: {len(cantidad_conversaciones_festivos)}")

print(f"Cantidad datos despues de ignorar: {cantidad_datos_filtrados}\n")

print(f"Anio: {year_rp} - Mes: {month_rp}")
print(f"Promedios conversaciones del mes 24h: \n")
print(f"Lunes: {promedios_24_h[0]}")
print(f"Martes: {promedios_24_h[1]}")
print(f"Miercoles: {promedios_24_h[2]}")
print(f"Jueves: {promedios_24_h[3]}")
print(f"Viernes: {promedios_24_h[4]}")
print(f"Sabado: {promedios_24_h[5]}")
print(f"Domingo: {promedios_24_h[6]} \n")

print("Promedios hora laboral")

# agregas columna con weekday
df_habiles = df.copy()
df_habiles['weekday'] = df_habiles['created_at'].dt.weekday

df_habiles = df_habiles[
    ((df_habiles['weekday'] != 6) & (df_habiles['weekday'] != 5) & (df_habiles['created_at'].dt.hour >=12) & (df_habiles['created_at'].dt.hour <=22)) | (
        (df_habiles['weekday'] == 5) &
        (df_habiles['created_at'].dt.hour >= 13) &
        (df_habiles['created_at'].dt.hour <= 17)
    )
]

# agrupas por weekday y día
promedios = (
    df_habiles.groupby([df_habiles['weekday'], df_habiles['created_at'].dt.to_period('D')])
    .size()
    .groupby(level=0)  # promedio por weekday
    .mean()
    .round(2)
)

ids_conversaciones_validas = df['id'].unique()
promedios

# Metrica  #2. Promedio de mensajes por hora

In [ ]:

sentencia_messages = "SELECT * FROM messages WHERE created_at >= '2025-11-01'" 

df_all_messages = pd.read_sql(sentencia_messages, engine)

df_messages = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()
df_messages = df_messages.sort_values(['conversation_id', 'created_at'])

df_messages = df_messages[(df_messages['sender_type'].notna()) & (df_messages['sender_type'] != 'User')]

df_messages['weekday'] = df_messages['created_at'].dt.weekday

promedios_por_hora_24h = (df_messages.groupby([df_messages['weekday'], df_messages['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))

print(f"Total mensajes de contactos en el mes: {len(df_messages)}\n")
print(f"Promedio mensajes de contactos en las 24h:")
print(f"Lunes: {promedios_por_hora_24h[0]}")
print(f"Martes: {promedios_por_hora_24h[1]}")
print(f"Miercoles: {promedios_por_hora_24h[2]}")
print(f"Jueves: {promedios_por_hora_24h[3]}")
print(f"Viernes: {promedios_por_hora_24h[4]}")
print(f"Sabado: {promedios_por_hora_24h[5]}")
print(f"Sabado: {promedios_por_hora_24h[6]} \n")


df_habiles_messag = df_messages[
    ((df_messages['weekday'] != 6) & (df_messages['weekday'] != 5) & (df_messages['created_at'].dt.hour >=12) & (df_messages['created_at'].dt.hour <=22)) | (
        (df_messages['weekday'] == 5) &
        (df_messages['created_at'].dt.hour >= 13) &
        (df_messages['created_at'].dt.hour <= 17)
    )
]
promedios_por_hora = (df_habiles_messag.groupby([df_habiles_messag['weekday'], df_habiles_messag['created_at'].dt.to_period('h')]).size().groupby(level=0).mean().round(2))
promedios_por_hora

print(f"Promedio mensajes de contactos en horario laboral:")
print(f"Lunes:{promedios_por_hora[0]}")
print(f"Martes: {promedios_por_hora[1]}")
print(f"Miercoles: {promedios_por_hora[2]}")
print(f"Jueves: {promedios_por_hora[3]}")
print(f"Viernes: {promedios_por_hora[4]}")
print(f"Sabado: {promedios_por_hora[5]}")

Total mensajes de contactos en el mes: 12461

Promedio mensajes de contactos en las 24h:
Lunes: 47.9
Martes: 42.02
Miercoles: 36.75
Jueves: 55.31
Viernes: 39.24
Sabado: 18.1
Sabado: 2.1

Promedio mensajes de contactos en horario laboral:
Lunes:55.12
Martes: 55.05
Miercoles: 47.93
Jueves: 73.86
Viernes: 55.51
Sabado: 35.89

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment,weekday
771,3205,Ortopedia,1,1,319,0,2025-11-04 12:46:39.818219,2025-11-04 12:46:39.818219,False,0,None,0,None,Contact,27.0,None,{},Ortopedia,{},1
728,3209,,1,1,319,0,2025-11-04 12:48:17.355426,2025-11-04 12:48:17.355426,False,0,None,0,None,Contact,27.0,None,{},,{},1
607,3192,"Mañana no voy a poder asistir, cuando podría s...",1,1,321,0,2025-11-04 12:29:42.681703,2025-11-04 12:29:42.681703,False,0,None,0,None,Contact,29.0,None,{},"Mañana no voy a poder asistir, cuando podría s...",{},1
608,3193,Con el Dr. Víctor Hugo ruiz,1,1,321,0,2025-11-04 12:30:01.773853,2025-11-04 12:30:01.773853,False,0,None,0,None,Contact,29.0,None,{},Con el Dr. Víctor Hugo ruiz,{},1
609,3194,Quedo pendiente gracias,1,1,321,0,2025-11-04 12:30:10.141473,2025-11-04 12:30:10.141473,False,0,None,0,None,Contact,29.0,None,{},Quedo pendiente gracias,{},1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34824,45225,Gracias,1,1,2752,0,2025-12-01 15:54:47.743782,2025-12-01 15:54:47.743782,False,0,None,0,None,Contact,1610.0,None,{},Gracias,{},0
41244,44506,Buenos dias,1,1,2753,0,2025-12-01 12:42:22.285766,2025-12-01 12:42:22.285766,False,0,None,0,None,Contact,1531.0,None,{},Buenos dias,{},0
41368,44509,.,1,1,2753,0,2025-12-01 12:42:30.865845,2025-12-01 12:42:30.865845,False,0,None,0,None,Contact,1531.0,None,{},.,{},0
41127,44510,Le envío resultado de creatinina,1,1,2753,0,2025-12-01 12:42:48.881715,2025-12-01 12:42:48.881715,False,0,None,0,None,Contact,1531.0,None,{},Le envío resultado de creatinina,{},0
40600,44514,,1,1,2753,0,2025-12-01 12:43:25.100682,2025-12-01 12:43:25.100682,False,0,None,0,None,Contact,1531.0,None,{},,{},0

## Hacer el promedio de primera respuesta solo de conversaciones que se crearon dentro del horario laboral

In [ ]:
# Promedio de primera respuesta de conversaciones que se iniciaron en cualquier hora y se calcula dependiendo de la la hora de la primera respuesta
# Por ejemplo: primer mensaje de usuario: miercoles 7pm; primera respuesta: 8:30am. Tiempo de primera respuesta = 90min


# Promedio de primera respuesta de conversaciones que se iniciaron solo en horario laboral, ignorando domingos, festivos y conversaciones que se crearon por fuera del horario laboral
# En este caso el ejemplo de arriba no aplica aqui porque la conversacion no se debe tomar en cuenta

# Metrica #3 Tiempo de Primera Respuesta

In [ ]:
df_sin_inicio_plantilla = df[~df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False)].copy()

#6501, 6807
df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_localize('UTC')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_localize('UTC')

df_sin_inicio_plantilla['created_at'] = df_sin_inicio_plantilla['created_at'].dt.tz_convert('America/Bogota')
df_sin_inicio_plantilla['first_reply_created_at'] = df_sin_inicio_plantilla['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia = df_sin_inicio_plantilla['created_at'].dt.date == df_sin_inicio_plantilla['first_reply_created_at'].dt.date

def calcular_dia_distinto(row):
    inicio = row['created_at']
    fin = row['first_reply_created_at']

    segundos = 0

    inicio_laboral_create_at = inicio.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_created_at = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    inicio_laboral_first_reply = fin.replace(hour=7, minute=0, second=0, microsecond=0)
    fin_laboral_first_reply = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        inicio_laboral_create_at = inicio.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_created_at = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
      
    if row['first_reply_created_at'].weekday() == 5:
        inicio_laboral_first_reply = fin.replace(hour=8, minute=0, second=0, microsecond=0)
        fin_laboral_first_reply = fin.replace(hour=12, minute=0, second=0, microsecond=0)
        

    if inicio >= inicio_laboral_create_at and inicio < fin_laboral_created_at and row['created_at'].weekday() != 6:
        segundos +=(fin_laboral_created_at-inicio).total_seconds()
    

    if fin > inicio_laboral_first_reply:
        segundos +=(fin - inicio_laboral_first_reply).total_seconds()
    
    return segundos

def calcular_mismo_dia(row):
    inicio = row['created_at']
    fin = row['first_reply_created_at']

    segundos = 0

    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)
    inicio_laboral = fin.replace(hour=7, minute=0, second=0, microsecond=0)

    if row['created_at'].weekday() == 5:
        fin_laboral = inicio.replace(hour=12, minute=0, second=0, microsecond=0)
        inicio_laboral = fin.replace(hour=8, minute=0, second=0, microsecond=0)

    if inicio >= inicio_laboral and inicio < fin_laboral :
        segundos +=(fin-inicio).total_seconds()
    
    if inicio < inicio_laboral and fin <= fin_laboral:
        segundos +=(fin-inicio_laboral).total_seconds()
    
    return df_habiles_messagmax(segundos, 0)
    
    
df_sin_inicio_plantilla['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    df_sin_inicio_plantilla.apply(calcular_mismo_dia, axis=1).round(2),
    df_sin_inicio_plantilla.apply(calcular_dia_distinto, axis=1).round(2)
)

df_sin_inicio_plantilla['tiempo_respuesta_minutos'] = (df_sin_inicio_plantilla['tiempo_respuesta_segundos'] / 60).round(2)
df_sin_inicio_plantilla['tiempo_respuesta_horas'] = (df_sin_inicio_plantilla['tiempo_respuesta_minutos'] / 60).round(2)

promedio_tiempo_respuesta_min = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].mean()
promedio_tiempo_respuesta_min


# print(df_sin_inicio_plantilla['tiempo_respuesta_minutos'].describe())
# v = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] ==  278.630000]
# v
# mitad = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] > 40]
# mitad.head(30)

print(df_sindf_habiles_messag_inicio_plantilla['tiempo_respuesta_minutos'].describe())
infiltrado = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] == 177.790000]
infiltrado

infiltrados = df_sin_inicio_plantilla[df_sin_inicio_plantilla['tiempo_respuesta_minutos'] >= 240]
infiltrados

## Promedio primera respuesta conversaciones iniciadas con plantilla

In [ ]:
# ids_caso_raro = [6175, 6877, 6214, 6057]
ids_conv_iniciadas_plantilla = df.loc[df['cached_label_list'].str.contains('iniciada_con_plantilla', na=False),'id']

#ids_conv_iniciadas_plantilla = ids_conv_iniciadas_plantilla[~ids_conv_iniciadas_plantilla.isin(ids_caso_raro)]

df_messages_conv_ini_plantilla = df_all_messages[df_all_messages['conversation_id'].isin(ids_conv_iniciadas_plantilla)].copy()
df_messages_conv_ini_plantilla = df_messages_conv_ini_plantilla.sort_values(['conversation_id', 'created_at'])

primer_mensadf_habiles_messagje_contacto = df_messages_conv_ini_plantilla[(df_messages_conv_ini_plantilla['message_type'] == 0) & (~df_messages_conv_ini_plantilla['content'].isin(['system_resolved', 'system_timeout']))].groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'created_at_type_0'})

df_merge_tiempo_primer_mensaje_contacto = df_messages_conv_ini_plantilla.merge(primer_mensaje_contacto, on='conversation_id', how='inner')

df_mensajes_agente = df_merge_tiempo_primer_mensaje_contacto[
    (df_merge_tiempo_primer_mensaje_contacto['message_type'] == 1) &
    (df_merge_tiempo_primer_mensaje_contacto['private'] != True) &
    (df_merge_tiempo_primer_mensaje_contacto['created_at'] > df_merge_tiempo_primer_mensaje_contacto['created_at_type_0'])
]

df_primera_respuesta = (df_mensajes_agente.sort_values(['conversation_id', 'created_at']).groupby('conversation_id', as_index=False).first()[['conversation_id', 'created_at']].rename(columns={'created_at': 'first_reply_created_at'}))

df_first_messages = primer_mensaje_contacto.merge(df_primera_respuesta,on='conversation_id',how='left')
df_first_messages = df_first_messages.rename(columns={'created_at_type_0': 'created_at'})

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_localize('UTC')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_localize('UTC')

df_first_messages['created_at'] = df_first_messages['created_at'].dt.tz_convert('America/Bogota')
df_first_messages['first_reply_created_at'] = df_first_messages['first_reply_created_at'].dt.tz_convert('America/Bogota')

mismo_dia_plantilla =  df_first_messages['created_at'].dt.date == df_first_messages['first_reply_created_at'].dt.date
df_first_messages['tiempo_respuesta_minutos'] = np.where(
    mismo_dia_plantilla,
    (df_first_messages.apply(calcular_mismo_dia, axis=1) / 60).round(2),
    (df_first_messages.apply(calcular_dia_distinto, axis=1) / 60).round(2)
)

promedio = df_first_messages['tiempo_respuesta_minutos'].mean() 
promedio

#v = df_first_messages[df_first_messages['tiempo_respuesta_minutos'] ==  197.010000]

total_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].sum()
cantidad_inicio_plantilla = df_first_messages['tiempo_respuesta_minutos'].count()

total_inicio_plantilla
cantidad_inicio_plantilla

total_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].sum()
cantidad_sin_inicio_plantilla = df_sin_inicio_plantilla['tiempo_respuesta_minutos'].count()

promedio_total = ((total_inicio_plantilla + total_sin_inicio_plantilla) / (cantidad_inicio_plantilla + cantidad_sin_inicio_plantilla)).round(2)
promedio_total




# df_first_messages

# Promedio primera respuesta conversaciones iniciadas solo en horario laboral

In [ ]:
df_filtrado = df_sin_inicio_plantilla[
    (
        df_sin_inicio_plantilla['created_at'].dt.weekday.between(0, 4) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_sin_inicio_plantilla['created_at'].dt.weekday == 5) &
        df_sin_inicio_plantilla['created_at'].dt.hour.between(8, 11)
    )
]

df_filtrado
total_minutos_df_filtrado = df_filtrado['tiempo_respuesta_minutos'].sum()
cantidad_conversaciones_df_filtrado = df_filtrado['tiempo_respuesta_minutos'].count()

p = total_minutos_df_filtrado / cantidad_conversaciones_df_filtrado
promedio_laboral = df_filtrado['tiempo_respuesta_minutos'].mean()



df_filtrado2 = df_first_messages[
     (
        df_first_messages['created_at'].dt.weekday.between(0, 4) &
        df_first_messages['created_at'].dt.hour.between(7, 16)
    ) |
    (
        (df_first_messages['created_at'].dt.weekday == 5) &
        df_first_messages['created_at'].dt.hour.between(8, 11)
    )
]
total_minutos_df_filtrado2 = df_filtrado2['tiempo_respuesta_minutos'].sum()
promedio_laboral2 = df_filtrado2['tiempo_respuesta_minutos'].mean()
df_filtrado2.shape
promedio_laboral2

# Metrica #4. Tiempo Promedio de Respuesta

Mediana del tiempo entre mensajes usuario → agente durante conversaciones activas.

In [ ]:
sentencia_messages_contact_user = "SELECT * FROM messages WHERE created_at >= '2025-11-01'"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])
df_messages_contact_user = df_messages_contact_user[df_messages_contact_user['conversation_id'].isin(ids_conversaciones_validas)]

df_messages_contact_user['next_message_type'] = df_messages_contact_user.groupby('conversation_id')['message_type'].shift(-1)
df_messages_contact_user['next_created_at'] = df_messages_contact_user.groupby('conversation_id')['created_at'].shift(-1)

respuestas = df_messages_contact_user[
    (df_messages_contact_user['message_type'] == 0) &
    (df_messages_contact_user['next_message_type'] == 1)
].copy()

respuestas['response_time_minutes'] = ((respuestas['next_created_at'] - respuestas['created_at']).dt.total_seconds() / 60).round(2)

promedio_por_conversacion = (respuestas.groupby('conversation_id')['response_time_minutes'].mean()).round(2) 

promedio_por_conversacion
# respuestas

# infiltrado = respuestas[respuestas['conversation_id'] == 6143]
# v = respuestas['response_time_minutes'].describe()
# v
# infiltrado

# Metrica #5. Conversión agendamiento (%)

In [ ]:
df_iniciadas_agendamiento = df[
    df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

agendamiento_exitoso = df_iniciadas_agendamiento[df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

iniciada_agendamiento = df_iniciadas_agendamiento[~df_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso')]

porcentaje_agendamiento_exitoso = (len(agendamiento_exitoso) / len(df_iniciadas_agendamiento)) * 100
porcentaje_agendamiento_no_exitoso = (len(iniciada_agendamiento) / len(df_iniciadas_agendamiento)) * 100

df_no_iniciadas_agendamiento = df[
    ~df['cached_label_list'].str.contains(
        r'(?:^|,)agendamiento(?:$|,)',
        regex=True,
        na=False
    )
]

no_iniciadas_agendamiento_agendadas = df_no_iniciadas_agendamiento[df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

no_iniciadas_agendamiento_no_agendadas = df_no_iniciadas_agendamiento[~df_no_iniciadas_agendamiento['cached_label_list'].str.contains('agendamiento_exitoso', na=False)]

len(no_iniciadas_agendamiento_no_agendadas)

porcentaje_no_iniciadas_agendamiento_agendadas = (len(no_iniciadas_agendamiento_agendadas) / len(df_no_iniciadas_agendamiento)) * 100
print(porcentaje_agendamiento_exitoso)
print(porcentaje_agendamiento_no_exitoso)

31.92090395480226
68.07909604519774

# Metrica #7. Índice de Eficiencia del Agente (AEI) [0–100]

In [ ]:
df = df.sort_values(['assignee_id'])
ids_contacts = df['contact_id'].unique()
df = df.sort_values(['contact_id'])
df.head()

# Metrica #9. Utilización de Capacidad (%)

In [137]:
df_messages_agent = df_all_messages[(df_all_messages['conversation_id'].isin(ids_conversaciones_validas))].copy()

df_messages_agent = df_messages_agent[
    ((df_messages_agent['created_at'].dt.weekday != 6) & (df_messages_agent['created_at'].dt.weekday != 5) & (df_messages_agent['created_at'].dt.hour >=12) & (df_messages_agent['created_at'].dt.hour <=22)) | (
        (df_messages_agent['created_at'].dt.weekday == 5) &
        (df_messages_agent['created_at'].dt.hour >= 13) &
        (df_messages_agent['created_at'].dt.hour <= 17)
    )
]

df_messages_agent = df_messages_agent[(df_messages_agent['sender_type'] == 'User') & (df_messages_agent['sender_id'] != 1)]
df_messages_agent = df_messages_agent.sort_values(['conversation_id', 'created_at'])
#tiempo estandar de escritura de un mensaje 40 PPM (palabras por minuto)
ppm = 40

df_messages_agent['cantidad_palabras'] = df_messages_agent['content'].fillna("").str.split().str.len()
df_messages_agent['tiempo_segundos_mensaje'] = (df_messages_agent['cantidad_palabras'] / ppm) * 60 


df_messages_agent['created_at'] = pd.to_datetime(df_messages_agent['created_at'])

df_prueba = (
    df_messages_agent
    .groupby([
        df_messages_agent['created_at'].dt.to_period('D'), 
        'sender_id'
    ])['tiempo_segundos_mensaje'].sum()
)

df_prueba.head(50)


# cant_id_agent = df_messages_agent['sender_id'].unique()
# cant_id_agent.shape
df_prueba
df_messages_agent

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,...,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment,cantidad_palabras,tiempo_segundos_mensaje
369,3260,AUTORIZADO},1,1,319,1,2025-11-04 13:26:53.545892,2025-11-04 13:26:53.545892,True,0,...,0,None,User,6.0,None,{},AUTORIZADO},{},1,1.5
319,3263,AUTORIZADO,1,1,319,1,2025-11-04 13:28:17.158055,2025-11-04 13:28:17.158055,True,0,...,0,None,User,6.0,None,{},AUTORIZADO,{},1,1.5
294,3332,IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comun...,1,1,331,1,2025-11-04 14:18:06.772246,2025-11-04 14:18:06.772246,False,0,...,0,None,User,6.0,None,{},IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comun...,{},120,180.0
785,3344,"Para programar su cita, por favor indíquenos l...",1,1,334,1,2025-11-04 14:21:37.919393,2025-11-04 14:21:37.919393,False,0,...,0,None,User,6.0,None,{},"Para programar su cita, por favor indíquenos l...",{},85,127.5
351,3356,con todo gusto,1,1,334,1,2025-11-04 14:30:58.663243,2025-11-04 14:30:58.663243,False,0,...,0,None,User,6.0,None,{},con todo gusto,{},3,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41261,44575,Muchas gracias por confirmar el resultado.,1,1,2753,1,2025-12-01 12:59:13.732829,2025-12-01 12:59:13.732829,False,0,...,0,None,User,10.0,None,{},Muchas gracias por confirmar el resultado.,{},6,9.0
41563,44576,¡Gracias por elegirnos! 💙 Esperamos poder aten...,1,1,2753,1,2025-12-01 12:59:18.089291,2025-12-01 12:59:18.089291,False,0,...,0,None,User,10.0,None,{},¡Gracias por elegirnos! 💙 Esperamos poder aten...,{},24,36.0
39793,44259,¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,1,1,2754,1,2025-12-01 12:00:08.314163,2025-12-01 12:00:08.314163,False,0,...,0,None,User,10.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,{},22,33.0
39250,44260,"Nos permitimos informar que, para la solicitud...",1,1,2754,1,2025-12-01 12:00:12.890056,2025-12-01 12:00:12.890056,False,0,...,0,None,User,10.0,None,{},"Nos permitimos informar que, para la solicitud...",{},99,148.5
39251,44261,¡Gracias por elegirnos! 💙 Esperamos poder aten...,1,1,2754,1,2025-12-01 12:00:17.372301,2025-12-01 12:00:17.372301,False,0,...,0,None,User,10.0,None,{},¡Gracias por elegirnos! 💙 Esperamos poder aten...,{},24,36.0

### Celula consultar datos

In [121]:
ids_caso_raro = [6175, 6877, 6214, 6057]
sentencia_messages_contact_user = "SELECT * FROM messages WHERE created_at::date = '2025-11-04' AND sender_type = 'User' AND sender_id = 6"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)

df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_localize('UTC')
df_messages_contact_user['created_at'] = df_messages_contact_user['created_at'].dt.tz_convert('America/Bogota')

df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])

df_messages_contact_user.head(90)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
5,3260,AUTORIZADO},1,1,319,1,2025-11-04 08:26:53.545892-05:00,2025-11-04 13:26:53.545892,True,0,None,0,None,User,6,None,{},AUTORIZADO},{}
2,3263,AUTORIZADO,1,1,319,1,2025-11-04 08:28:17.158055-05:00,2025-11-04 13:28:17.158055,True,0,None,0,None,User,6,None,{},AUTORIZADO,{}
9,3257,"Nos permitimos informar que, para la solicitud...",1,1,326,1,2025-11-04 08:23:55.265264-05:00,2025-11-04 13:23:55.265264,False,0,None,0,None,User,6,None,{},"Nos permitimos informar que, para la solicitud...",{}
1,3332,IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comun...,1,1,331,1,2025-11-04 09:18:06.772246-05:00,2025-11-04 14:18:06.772246,False,0,None,0,None,User,6,None,{},IMÁGENES DIAGNÓSTICAS S.A. 😊 agradece su comun...,{}
18,3344,"Para programar su cita, por favor indíquenos l...",1,1,334,1,2025-11-04 09:21:37.919393-05:00,2025-11-04 14:21:37.919393,False,0,None,0,None,User,6,None,{},"Para programar su cita, por favor indíquenos l...",{}
4,3356,con todo gusto,1,1,334,1,2025-11-04 09:30:58.663243-05:00,2025-11-04 14:30:58.663243,False,0,None,0,None,User,6,None,{},con todo gusto,{}
6,3384,adjunto soporte de cita por favor *DESDE 3 DIA...,1,1,334,1,2025-11-04 09:41:35.179913-05:00,2025-11-04 14:41:35.179913,False,0,None,0,None,User,6,None,{},adjunto soporte de cita por favor *DESDE 3 DIA...,{}
7,3385,este dia se le tomarán los 3 exámenes solicita...,1,1,334,1,2025-11-04 09:42:45.602608-05:00,2025-11-04 14:42:45.602608,False,0,None,0,None,User,6,None,{},este dia se le tomarán los 3 exámenes solicita...,{}
12,3448,por favor visualizar el documento enviado ante...,1,1,334,1,2025-11-04 10:28:36.639879-05:00,2025-11-04 15:28:36.639879,False,0,None,0,None,User,6,None,{},por favor visualizar el documento enviado ante...,{}
13,3453,None,1,1,334,1,2025-11-04 10:28:52.291050-05:00,2025-11-04 15:28:52.291050,False,0,None,0,None,User,6,None,{},None,{}
15,3460,"\r\nSon 3 examenes\r\n\r\nNov 4, 9:31 AM\r\nad...",1,1,334,1,2025-11-04 10:30:07.328298-05:00,2025-11-04 15:30:07.328298,False,0,None,0,None,User,6,None,{},"\r\nSon 3 examenes\r\n\r\nNov 4, 9:31 AM\r\nad...",{}
16,3461,descargalo por favor,1,1,334,1,2025-11-04 10:30:34.139727-05:00,2025-11-04 15:30:34.139727,False,0,None,0,"{""in_reply_to"":3453,""in_reply_to_external_id"":...",User,6,None,{},descargalo por favor,{}
17,3485,"mil disculpas error de sistema, ya se lo envia...",1,1,334,1,2025-11-04 10:35:03.356272-05:00,2025-11-04 15:35:03.356272,False,0,None,0,None,User,6,None,{},"mil disculpas error de sistema, ya se lo envia...",{}
19,3489,¡Gracias por elegirnos! 💙 Esperamos poder aten...,1,1,334,1,2025-11-04 10:37:50.792397-05:00,2025-11-04 15:37:50.792397,False,0,None,0,None,User,6,None,{},¡Gracias por elegirnos! 💙 Esperamos poder aten...,{}
10,3454,hola,1,1,341,1,2025-11-04 10:29:09.456016-05:00,2025-11-04 15:29:09.456016,False,0,None,0,None,User,6,None,{},hola,{}
11,3456,adjunto soporte de cita por favor *DESDE 3 DIA...,1,1,341,1,2025-11-04 10:29:35.207466-05:00,2025-11-04 15:29:35.207466,False,0,None,0,None,User,6,None,{},adjunto soporte de cita por favor *DESDE 3 DIA...,{}
14,3458,adjunto soporte de cita por favor DESDE 3 DIAS...,1,1,341,1,2025-11-04 10:29:46.960931-05:00,2025-11-04 15:29:46.960931,False,0,None,0,None,User,6,None,{},adjunto soporte de cita por favor DESDE 3 DIAS...,{}
0,3474,hola,1,1,342,1,2025-11-04 10:31:40.377451-05:00,2025-11-04 15:31:40.377451,False,0,None,0,None,User,6,None,{},hola,{}
3,3476,None,1,1,342,1,2025-11-04 10:31:45.728027-05:00,2025-11-04 15:31:45.728027,False,0,None,0,None,User,6,None,{},None,{}
8,3477,"\r\nSon 3 examenes\r\n\r\nNov 4, 9:31 AM\r\nad...",1,1,342,1,2025-11-04 10:31:49.158344-05:00,2025-11-04 15:31:49.158344,False,0,None,0,None,User,6,None,{},"\r\nSon 3 examenes\r\n\r\nNov 4, 9:31 AM\r\nad...",{}