In [ ]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://intern_new:internpass_new@localhost:5434/intern_db_new")

In [211]:
sentencia = "SELECT * FROM conversations WHERE created_at >= '2025-11-01' AND first_reply_created_at IS NOT NULL"

df = pd.read_sql(sentencia, engine)

contactos = pd.read_sql("SELECT * FROM contacts WHERE name ~ '[A-Za-z]'", engine)
lista_ignorar_contactos = contactos['id'].unique()
lista_ignorar_contactos.tolist()

ids_conversaciones_ignorar = df.loc[df['contact_id'].isin(lista_ignorar_contactos), 'id']

df = df[~df['contact_id'].isin(lista_ignorar_contactos)]

df['created_at'] = pd.to_datetime(df['created_at'])

df_laboral = df[(df['created_at'].dt.weekday < 5) |  ((df['created_at'].dt.weekday == 5) &  (df['created_at'].dt.hour < 12))].copy()


conversaciones_por_dia = df_laboral.groupby(df_laboral['created_at'].dt.to_period('D')).size()


promedio_conversaciones_diarias = conversaciones_por_dia.mean()
promedio_conversaciones_diarias

np.float64(88.55384615384615)

In [202]:
sentencia_messages = "SELECT * FROM messages WHERE sender_type IS NOT NULL AND sender_type != 'User'" 


df_messages = pd.read_sql(sentencia_messages, engine)
df_messages = df_messages[~df_messages['conversation_id'].isin(ids_conversaciones_ignorar)]
mensajes_por_hora = df_messages.groupby(df_messages['created_at'].dt.to_period('h')).size()
promedio_mensajes_por_hora = mensajes_por_hora.mean().round(2)

promedio_mensajes_por_hora

np.float64(33.55)

In [284]:
# df_laboral['created_at'] = df_laboral['created_at'].dt.tz_localize('UTC')
# df_laboral['first_reply_created_at'] = df_laboral['first_reply_created_at'].dt.tz_localize('UTC')

df_laboral['created_at'] = df_laboral['created_at'].dt.tz_convert('America/Bogota')
df_laboral['first_reply_created_at'] = df_laboral['first_reply_created_at'].dt.tz_convert('America/Bogota')



mismo_dia = df_laboral['created_at'].dt.date == df_laboral['first_reply_created_at'].dt.date
def calcular_dia_distinto(row):
    inicio = row['created_at']
    
    fin = row['first_reply_created_at']


    segundos = 0
    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    if inicio < fin_laboral:
        segundos +=(fin_laboral-inicio).total_seconds()
    
    inicio_laboral = fin.replace(hour=7, minute=0, second=0, microsecond=0)

    if fin > inicio_laboral:
        segundos +=(fin - inicio_laboral).total_seconds()
    
    return max(segundos, 0)

df_laboral['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    (df_laboral['first_reply_created_at']-df_laboral['created_at']).dt.total_seconds().round(2),
    df_laboral.apply(calcular_dia_distinto, axis=1).round(2)
)


df_laboral['tiempo_respuesta_minutos'] = (df_laboral['tiempo_respuesta_segundos'] / 60).round(2)
df_laboral['tiempo_respuesta_horas'] = (df_laboral['tiempo_respuesta_minutos'] / 60).round(2)

df_laboral.head(10)

tiempo_total_respuesta_individual = (df_laboral.groupby('contact_id')['tiempo_respuesta_segundos'].mean()) / 60 
# tiempo_total_respuesta_individual_min = tiempo_total_respuesta_individual_seg / 60
# tiempo_total_respuesta_individual_horas = tiempo_total_respuesta_individual_min / 60

promedio_tiempo_respuesta_general_min = df_laboral['tiempo_respuesta_minutos'].mean()
promedio_tiempo_respuesta_general_min

tiempo_total_respuesta_individual.head(30)


df_laboral.head(30)

,id,account_id,inbox_id,status,assignee_id,created_at,updated_at,contact_id,display_id,contact_last_seen_at,...,custom_attributes,assignee_last_seen_at,first_reply_created_at,priority,sla_policy_id,waiting_since,cached_label_list,tiempo_respuesta_segundos,tiempo_respuesta_minutos,tiempo_respuesta_horas
748,1148,1,1,1,1.0,2025-11-17 20:48:29.496242-05:00,2025-11-18 01:51:54.746621,19,1148,None,...,{},2025-11-18 01:51:54.863121,2025-11-17 20:48:29.506161-05:00,NaN,None,NaT,iniciada_con_plantilla,0.01,0.00,0.00
130,319,1,1,1,NaN,2025-11-04 06:52:18.199918-05:00,2025-11-04 13:35:50.483685,27,319,None,...,{},2025-11-04 13:35:50.556647,2025-11-04 08:04:54.330977-05:00,0.0,None,NaT,agendamiento,4356.13,72.60,1.21
41,320,1,1,1,NaN,2025-11-04 06:59:56.551432-05:00,2025-11-04 14:38:09.174962,28,320,None,...,{},2025-11-04 14:38:09.253493,2025-11-04 07:55:35.840898-05:00,0.0,None,NaT,agendamiento,3339.29,55.65,0.93
1887,2320,1,1,1,NaN,2025-11-26 09:18:03.168174-05:00,2025-11-26 14:32:19.450570,29,2320,None,...,{},2025-11-26 14:23:15.342369,2025-11-26 09:18:03.193668-05:00,NaN,None,NaT,iniciada_con_plantilla,0.03,0.00,0.00
19,321,1,1,1,NaN,2025-11-04 07:29:42.598828-05:00,2025-11-04 15:10:25.272329,29,321,None,...,{},2025-11-04 15:23:00.051161,2025-11-04 07:56:13.355787-05:00,0.0,None,NaT,,1590.76,26.51,0.44
20,338,1,1,1,NaN,2025-11-04 09:57:32.410616-05:00,2025-11-04 15:49:45.863068,29,338,None,...,{},2025-11-04 15:49:45.936321,2025-11-04 09:59:45.059288-05:00,0.0,None,NaT,reprogramacion,132.65,2.21,0.04
3363,3845,1,1,1,NaN,2025-12-11 12:03:20.291656-05:00,2025-12-11 20:34:39.977491,29,3845,None,...,{},NaT,2025-12-11 13:06:58.755658-05:00,0.0,None,NaT,,3818.46,63.64,1.06
123,322,1,1,1,NaN,2025-11-04 07:32:20.903116-05:00,2025-11-04 13:01:13.202262,30,322,None,...,{},2025-11-04 13:01:13.275776,2025-11-04 07:52:36.663664-05:00,0.0,None,NaT,otro,1215.76,20.26,0.34
1838,2287,1,1,1,10.0,2025-11-25 15:56:41.209685-05:00,2025-11-25 22:04:35.829403,31,2287,None,...,{},2025-11-25 22:04:35.921739,2025-11-25 15:58:16.586813-05:00,0.0,None,NaT,agendamiento_exitoso,95.38,1.59,0.03
93,339,1,1,1,NaN,2025-11-04 10:06:35.569105-05:00,2025-11-04 16:03:13.905385,31,339,None,...,{},2025-11-04 16:03:13.972624,2025-11-04 10:09:22.224334-05:00,0.0,None,NaT,,166.66,2.78,0.05
807,325,1,1,1,NaN,2025-11-04 07:56:16.292990-05:00,2025-11-04 14:38:06.244260,31,325,None,...,{},2025-11-04 14:38:06.304382,2025-11-04 07:57:30.363367-05:00,0.0,None,NaT,,74.07,1.23,0.02
1990,2431,1,1,1,NaN,2025-11-26 16:26:11.041572-05:00,2025-11-27 13:11:06.738815,31,2431,None,...,{},NaT,2025-11-27 07:12:33.986652-05:00,0.0,None,NaT,cancelacion,2782.95,46.38,0.77
125,327,1,1,1,NaN,2025-11-04 08:30:06.106475-05:00,2025-11-04 13:45:27.045052,32,327,None,...,{},2025-11-04 13:45:27.120342,2025-11-04 08:41:34.813751-05:00,0.0,None,NaT,agendamiento,688.71,11.48,0.19
6152,6501,1,1,1,12.0,2026-01-14 11:18:05.047403-05:00,2026-01-15 15:25:57.149538,33,6501,None,...,{},2026-01-15 15:25:57.218006,2026-01-14 15:56:42.601575-05:00,0.0,None,NaT,agendamiento,16717.55,278.63,4.64
781,328,1,1,1,NaN,2025-11-04 08:45:01.134454-05:00,2025-11-04 13:48:27.002378,33,328,None,...,{},2025-11-04 13:48:27.079431,2025-11-04 08:46:17.850720-05:00,0.0,None,NaT,cancelacion,76.72,1.28,0.02
1746,2167,1,1,1,15.0,2025-11-24 17:34:22.191415-05:00,2025-11-25 14:50:46.963710,33,2167,None,...,{},2025-11-25 14:42:43.984787,2025-11-25 07:08:15.018506-05:00,0.0,None,NaT,agendamiento_exitoso,495.02,8.25,0.14
4803,5363,1,1,1,NaN,2025-12-31 08:42:03.660382-05:00,2025-12-31 15:03:05.004661,33,5363,None,...,{},NaT,2025-12-31 08:50:12.690725-05:00,0.0,None,NaT,"agendamiento, agendamiento_exitoso",489.03,8.15,0.14
793,330,1,1,1,NaN,2025-11-04 08:59:19.414137-05:00,2025-11-04 14:09:18.188896,34,330,None,...,{},2025-11-04 14:09:18.258081,2025-11-04 09:07:06.464532-05:00,0.0,None,NaT,agendamiento,467.05,7.78,0.13
60,331,1,1,1,6.0,2025-11-04 09:15:28.466903-05:00,2025-11-04 14:18:14.146257,35,331,None,...,{},2025-11-11 12:35:31.766465,2025-11-04 09:18:06.772246-05:00,0.0,None,NaT,agendamiento,158.31,2.64,0.04
65,335,1,1,1,12.0,2025-11-04 09:19:47.840429-05:00,2025-11-04 20:06:53.929992,35,335,None,...,{},2025-11-04 20:06:54.021773,2025-11-04 11:10:14.522075-05:00,0.0,None,NaT,,6626.68,110.44,1.84
792,333,1,1,1,NaN,2025-11-04 09:17:15.623318-05:00,2025-11-04 15:38:09.759695,36,333,None,...,{},2025-11-04 15:38:09.821641,2025-11-04 09:31:12.481130-05:00,0.0,None,NaT,,836.86,13.95,0.23
62,334,1,1,1,6.0,2025-11-04 09:17:49.904773-05:00,2025-11-04 15:37:53.650293,37,334,None,...,{},2025-11-11 12:35:28.677133,2025-11-04 09:21:37.919393-05:00,0.0,None,NaT,agendamiento,228.01,3.80,0.06
804,337,1,1,1,NaN,2025-11-04 09:47:27.334340-05:00,2025-11-04 15:40:58.779392,38,337,None,...,{},2025-11-04 15:40:58.849629,2025-11-04 09:47:45.347204-05:00,0.0,None,NaT,agendamiento,18.01,0.30,0.00
121,385,1,1,1,12.0,2025-11-05 08:13:59.390419-05:00,2025-11-05 15:10:01.557672,38,385,None,...,{},2025-11-05 15:10:01.628757,2025-11-05 08:29:14.492858-05:00,0.0,None,NaT,cancelacion,915.10,15.25,0.25
784,340,1,1,1,NaN,2025-11-04 10:20:53.070554-05:00,2025-11-04 16:52:12.090551,39,340,None,...,{},2025-11-04 16:19:29.027340,2025-11-04 10:21:32.618589-05:00,0.0,None,NaT,"agendamiento, agendamiento_exitoso",39.55,0.66,0.01
811,343,1,1,1,NaN,2025-11-04 10:41:33.521433-05:00,2025-11-04 16:15:56.918758,40,343,None,...,{},2025-11-04 16:15:56.975679,2025-11-04 10:43:17.986978-05:00,0.0,None,2025-11-04 15:49:23.327823,,104.47,1.74,0.03
4170,4643,1,1,1,NaN,2025-12-19 11:06:25.656531-05:00,2025-12-19 21:35:01.773028,40,4643,None,...,{},NaT,2025-12-19 11:25:00.539718-05:00,0.0,None,NaT,otro,1114.88,18.58,0.31
3636,4155,1,1,1,NaN,2025-12-15 11:42:37.392415-05:00,2025-12-16 13:13:24.549908,40,4155,None,...,{},NaT,2025-12-15 12:01:47.786900-05:00,0.0,None,NaT,"reprogramacion, agendamiento_exitoso",1150.39,19.17,0.32
4204,4772,1,1,1,10.0,2025-12-22 08:18:21.764862-05:00,2025-12-23 14:36:56.724264,40,4772,None,...,{},2025-12-23 14:36:56.856496,2025-12-22 08:18:21.791392-05:00,NaN,None,NaT,iniciada_con_plantilla,0.03,0.00,0.00
3285,3704,1,1,1,NaN,2025-12-10 13:55:50.054310-05:00,2025-12-10 22:31:35.950449,40,3704,None,...,{},NaT,2025-12-10 14:27:13.668560-05:00,0.0,None,NaT,serivicios_y_tarifas,1883.61,31.39,0.52

In [285]:
sentencia_messages_contact_user = "SELECT * FROM messages"
df_messages_contact_user = pd.read_sql(sentencia_messages_contact_user, engine)


df_messages_contact_user = df_messages_contact_user.sort_values(['conversation_id', 'created_at'])

df_messages_contact_user['next_message_type'] = df_messages_contact_user.groupby('conversation_id')['message_type'].shift(-1)
df_messages_contact_user['next_created_at'] = df_messages_contact_user.groupby('conversation_id')['created_at'].shift(-1)

respuestas = df_messages_contact_user[
    (df_messages_contact_user['message_type'] == 0) &
    (df_messages_contact_user['next_message_type'] == 1)
].copy()

respuestas['response_time_seconds'] = ((respuestas['next_created_at'] - respuestas['created_at']).dt.total_seconds() / 60).round(2)

promedio_por_conversacion = (respuestas.groupby('conversation_id')['response_time_seconds'].mean()).round(2)


df_messages_contact_user

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,...,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment,next_message_type,next_created_at
10,16,Asignado a cer por Jacobo Ruiz,1,1,4,2,2025-05-24 01:16:31.773094,2025-05-24 01:16:31.773094,False,0,...,0,None,None,NaN,None,{},Asignado a cer por Jacobo Ruiz,{},1.0,2025-05-28 18:49:48.836617
27,33,gooday,1,1,4,1,2025-05-28 18:49:48.836617,2025-05-28 18:49:48.836617,False,0,...,0,None,User,1.0,None,{},gooday,{},2.0,2025-05-28 18:50:05.963978
28,34,La conversación fue marcada por Jacobo Ruiz,1,1,4,2,2025-05-28 18:50:05.963978,2025-05-28 18:50:05.963978,False,0,...,0,None,None,NaN,None,{},La conversación fue marcada por Jacobo Ruiz,{},NaN,NaT
11,17,Asignado a cer por Jacobo Ruiz,1,1,5,2,2025-05-24 01:18:45.592341,2025-05-24 01:18:45.592341,False,0,...,0,None,None,NaN,None,{},Asignado a cer por Jacobo Ruiz,{},1.0,2025-05-28 18:42:37.050526
25,31,this is a conversation we will close,1,1,5,1,2025-05-28 18:42:37.050526,2025-05-28 18:42:37.050526,False,0,...,0,None,User,1.0,None,{},this is a conversation we will close,{},2.0,2025-05-28 18:45:16.403252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118375,120522,#plantilla_inicial SEGUIMIENTO_SOLICITUD {Jenn...,1,1,7047,1,2026-01-19 19:08:44.901972,2026-01-19 19:08:44.901972,False,0,...,0,None,User,12.0,None,{},#plantilla_inicial SEGUIMIENTO_SOLICITUD {Jenn...,{},2.0,2026-01-19 19:08:44.925042
118341,120523,Jenny auto-asignado a esta conversación,1,1,7047,2,2026-01-19 19:08:44.925042,2026-01-19 19:08:44.925042,False,0,...,0,None,None,NaN,None,{},Jenny auto-asignado a esta conversación,{},2.0,2026-01-19 19:08:44.996055
118360,120524,Automation System agregó iniciada_con_plantilla,1,1,7047,2,2026-01-19 19:08:44.996055,2026-01-19 19:08:44.996055,False,0,...,0,None,None,NaN,None,{},Automation System agregó iniciada_con_plantilla,{},2.0,2026-01-19 19:08:45.058535
118146,120525,Asignado a cer por Sistema,1,1,7047,2,2026-01-19 19:08:45.058535,2026-01-19 19:08:45.058535,False,0,...,0,None,None,NaN,None,{},Asignado a cer por Sistema,{},1.0,2026-01-19 19:08:48.447107
118376,120526,SISTEMA: El mensaje inicial fue recibido por e...,1,1,7047,1,2026-01-19 19:08:48.447107,2026-01-19 19:08:48.447107,True,0,...,0,None,User,1.0,None,{},SISTEMA: El mensaje inicial fue recibido por e...,{},NaN,NaT

In [ ]:
# ids_conversations = df_messages_contact_user['conversation_id'].unique()

# def analisis(lista_id):
#     dicc = {}
#     for id in lista_id:
#         df_funcion = pd.read_sql(f"SELECT * FROM messages WHERE conversation_id = {id}", engine)

#         dicc[id] = df_funcion
#     return dicc
# ids_conversations = ids_conversations.tolist()
# resultado = analisis(ids_conversations)

,id,content,account_id,inbox_id,conversation_id,message_type,created_at,updated_at,private,status,source_id,content_type,content_attributes,sender_type,sender_id,external_source_ids,additional_attributes,processed_message_content,sentiment
0,9820,¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,1,1,736,1,2025-11-13 13:03:58.917519,2025-11-13 13:03:58.917519,False,0,None,0,None,User,6.0,None,{},¡Hola! 👋Bienvenido/a al canal exclusivo de asi...,{}
1,9830,ofrecemos disculpas presentamos una actualizac...,1,1,736,1,2025-11-13 13:05:03.718563,2025-11-13 13:05:03.718563,False,0,None,0,None,User,6.0,None,{},ofrecemos disculpas presentamos una actualizac...,{}
2,9821,Por favor podría responder a mi solicitud,1,1,736,0,2025-11-13 13:04:21.153461,2025-11-13 13:04:21.153461,False,0,None,0,None,Contact,315.0,None,{},Por favor podría responder a mi solicitud,{}
3,9824,Ayer me dijeron para agendar cita para el sába...,1,1,736,0,2025-11-13 13:04:53.534174,2025-11-13 13:04:53.534174,False,0,None,0,None,Contact,315.0,None,{},Ayer me dijeron para agendar cita para el sába...,{}
4,9857,,1,1,736,0,2025-11-13 13:07:36.847836,2025-11-13 13:07:36.847836,False,0,None,0,None,Contact,315.0,None,{},,{}
5,9871,Para el sábado correcto?,1,1,736,0,2025-11-13 13:09:52.939943,2025-11-13 13:09:52.939943,False,0,None,0,None,Contact,315.0,None,{},Para el sábado correcto?,{}
6,9876,nos informabas ayer que el paciente tolera sin...,1,1,736,1,2025-11-13 13:10:35.243301,2025-11-13 13:10:35.243301,False,0,None,0,None,User,6.0,None,{},nos informabas ayer que el paciente tolera sin...,{}
7,9934,La conversación fue marcada por Andrés Echeverri,1,1,736,2,2025-11-13 13:20:00.146381,2025-11-13 13:20:00.146381,False,0,None,0,None,None,NaN,None,{},La conversación fue marcada por Andrés Echeverri,{}
8,9936,Andrés Echeverri agregó agendamiento_exitoso,1,1,736,2,2025-11-13 13:20:28.621423,2025-11-13 13:20:28.621423,False,0,None,0,None,None,NaN,None,{},Andrés Echeverri agregó agendamiento_exitoso,{}
9,9848,"Para programar su cita, por favor indíquenos l...",1,1,736,0,2025-11-13 13:06:56.253019,2025-11-13 13:06:56.253019,False,0,None,0,None,Contact,315.0,None,{},"Para programar su cita, por favor indíquenos l...",{}
10,9854,Por la complejidad del procedimiento solicitad...,1,1,736,0,2025-11-13 13:07:15.109979,2025-11-13 13:07:15.109979,False,0,None,0,None,Contact,315.0,None,{},Por la complejidad del procedimiento solicitad...,{}
11,9851,Mathias Sebastian zambrano Marquez\r\n\r\nPt 5...,1,1,736,0,2025-11-13 13:07:04.146012,2025-11-13 13:07:04.146012,False,0,None,0,None,Contact,315.0,None,{},Mathias Sebastian zambrano Marquez\r\n\r\nPt 5...,{}
12,9855,No\r\n\r\nNo\r\n\r\nNo\r\n\r\n42kg\r\n\r\nNo\r...,1,1,736,0,2025-11-13 13:07:25.202454,2025-11-13 13:07:25.202454,False,0,None,0,None,Contact,315.0,None,{},No\r\n\r\nNo\r\n\r\nNo\r\n\r\n42kg\r\n\r\nNo\r...,{}
13,9863,muchas gracias ya le envío el soporte de su cita,1,1,736,1,2025-11-13 13:08:45.525222,2025-11-13 13:08:45.525222,False,0,None,0,None,User,6.0,None,{},muchas gracias ya le envío el soporte de su cita,{}
14,9869,Perfecto muchas gracias 🫂,1,1,736,0,2025-11-13 13:09:18.303985,2025-11-13 13:09:18.303985,False,0,None,0,None,Contact,315.0,None,{},Perfecto muchas gracias 🫂,{}
15,9904,Si sin sedaccion,1,1,736,0,2025-11-13 13:16:38.532592,2025-11-13 13:16:38.532592,False,0,None,0,None,Contact,315.0,None,{},Si sin sedaccion,{}
16,9909,adjunto soporte de cita por favor Traer orden ...,1,1,736,1,2025-11-13 13:17:25.470021,2025-11-13 13:17:25.470021,False,0,None,0,None,User,6.0,None,{},adjunto soporte de cita por favor Traer orden ...,{}
17,9928,Muchas gracias amigo,1,1,736,0,2025-11-13 13:18:31.518619,2025-11-13 13:18:31.518619,False,0,None,0,None,Contact,315.0,None,{},Muchas gracias amigo,{}
18,9929,le otorgamos un descuento y solo debe cancelar...,1,1,736,1,2025-11-13 13:18:59.972169,2025-11-13 13:18:59.972169,False,0,None,0,None,User,6.0,None,{},le otorgamos un descuento y solo debe cancelar...,{}
19,9890,Si requiere sedaccion como sería el proceso?,1,1,736,0,2025-11-13 13:13:07.038257,2025-11-13 13:13:07.038257,False,0,None,0,None,Contact,315.0,None,{},Si requiere sedaccion como sería el proceso?,{}
20,9899,si desea programamos la resonancia para el sáb...,1,1,736,1,2025-11-13 13:15:12.485962,2025-11-13 13:15:12.485962,False,0,None,0,None,User,6.0,None,{},si desea programamos la resonancia para el sáb...,{}
21,9905,perfecto,1,1,736,1,2025-11-13 13:16:43.461203,2025-11-13 13:16:43.461203,False,0,None,0,None,User,6.0,None,{},perfecto,{}
22,9896,debe contar con solicitud en la orden y tiene ...,1,1,736,1,2025-11-13 13:13:58.442442,2025-11-13 13:13:58.442442,False,0,None,0,None,User,6.0,None,{},debe contar con solicitud en la orden y tiene ...,{}
23,9918,None,1,1,736,1,2025-11-13 13:17:41.226977,2025-11-13 13:17:41.226977,False,0,None,0,None,User,6.0,None,{},None,{}
24,9906,None,1,1,736,1,2025-11-13 13:16:53.109734,2025-11-13 13:16:53.109734,False,0,None,0,None,User,6.0,None,{},None,{}
25,9910,None,1,1,736,1,2025-11-13 13:17:36.183419,2025-11-13 13:17:36.183419,False,0,None,0,None,User,6.0,None,{},None,{}
26,9933,¡Gracias por elegirnos! 💙 Esperamos poder aten...,1,1,736,1,2025-11-13 13:19:58.683899,2025-11-13 13:19:58.683899,False,0,None,0,None,User,6.0,None,{},¡Gracias por elegirnos! 💙 Esperamos poder aten...,{}
27,9733,Asignado a Andrés Echeverri via canal dedicado...,1,1,736,2,2025-11-13 12:49:58.791729,2025-11-13 12:49:58.791729,False,0,None,0,None,None,NaN,None,{},Asignado a Andrés Echeverri via canal dedicado...,{}
28,9734,Sistema agregó agendamiento,1,1,736,2,2025-11-13 12:49:58.852167,2025-11-13 12:49:58.852167,False,0,None,0,None,None,NaN,None,{},Sistema agregó agendamiento,{}
29,9735,SISTEMA: paciente esta interesado en AGENDAR u...,1,1,736,1,2025-11-13 12:49:58.868889,2025-11-13 12:49:58.868889,True,0,None,0,None,User,1.0,None,{},SISTEMA: paciente esta interesado en AGENDAR u...,{}
30,9738,,1,1,736,0,2025-11-13 12:50:17.702203,2025-11-13 12:50:17.702203,False,0,None,0,None,Contact,315.0,None,{},,{}
31,9739,Resonancia magnética nuclear de cerebro,1,1,736,0,2025-11-13 12:50:28.149379,2025-11-13 12:50:28.149379,False,0,None,0,None,Contact,315.0,None,{},Resonancia magnética nuclear de cerebro,{}
32,9736,Sistema estableció la prioridad a low,1,1,736,2,2025-11-13 12:49:58.873831,2025-11-13 12:49:58.873831,False,0,None,0,None,None,NaN,None,{},Sistema estableció la prioridad a low,{}
33,9746,Desde ayer estoy esperando la confirmación de ...,1,1,736,0,2025-11-13 12:53:17.957064,2025-11-13 12:53:17.957064,False,0,None,0,None,Contact,315.0,None,{},Desde ayer estoy esperando la confirmación de ...,{}

In [ ]:
# df_laboral['created_at'] = df_laboral['created_at'].dt.tz_localize('UTC')
# df_laboral['first_reply_created_at'] = df_laboral['first_reply_created_at'].dt.tz_localize('UTC')

df_laboral['created_at'] = df_laboral['created_at'].dt.tz_convert('America/Bogota')
df_laboral['first_reply_created_at'] = df_laboral['first_reply_created_at'].dt.tz_convert('America/Bogota')



mismo_dia = df_laboral['created_at'].dt.date == df_laboral['first_reply_created_at'].dt.date
def calcular_dia_distinto(row):
    inicio = row['created_at']
    
    fin = row['first_reply_created_at']


    segundos = 0
    fin_laboral = inicio.replace(hour=17, minute=0, second=0, microsecond=0)

    if inicio < fin_laboral:
        segundos +=(fin_laboral-inicio).total_seconds()
    
    inicio_laboral = fin.replace(hour=7, minute=0, second=0, microsecond=0)

    if fin > inicio_laboral:
        segundos +=(fin - inicio_laboral).total_seconds()
    
    return max(segundos, 0)

df_laboral['tiempo_respuesta_segundos'] = np.where(
    mismo_dia,
    (df_laboral['first_reply_created_at']-df_laboral['created_at']).dt.total_seconds().round(2),
    df_laboral.apply(calcular_dia_distinto, axis=1).round(2)
)


df_laboral['tiempo_respuesta_minutos'] = (df_laboral['tiempo_respuesta_segundos'] / 60).round(2)
df_laboral['tiempo_respuesta_horas'] = (df_laboral['tiempo_respuesta_minutos'] / 60).round(2)

df_laboral.head(10)

# tiempo_total_respuesta_individual_seg = df.groupby('contact_id')['tiempo_respuesta_segundos'].sum() 
# tiempo_total_respuesta_individual_min = tiempo_total_respuesta_individual_seg / 60
# tiempo_total_respuesta_individual_horas = tiempo_total_respuesta_individual_min / 60

promedio_tiempo_respuesta_general_min = df_laboral['tiempo_respuesta_minutos'].mean()
promedio_tiempo_respuesta_general_min

np.float64(28.835691452397498)

TypeError: 'int' object is not subscriptable