In [161]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://intern:internpass@localhost:5433/intern_db"
)

In [197]:
df_sessions = pd.read_sql("SELECT * FROM sessions;", engine)
lista = []

#df_sessions = df_sessions[~df_sessions['user_id'].isin(lista)]
df_sessions['start_time'] = pd.to_datetime(df_sessions['start_time'])
df_sessions['end_time'] = pd.to_datetime(df_sessions['end_time'])


df_sessions['duracion_session_min'] = ((df_sessions['end_time']-df_sessions['start_time']).dt.total_seconds() / 60).round(2)
df_sessions['duracion_session_horas'] = df_sessions['duracion_session_min'] / 60

df_session_mayor_8_horas = df_sessions[df_sessions['duracion_session_horas'] > 8]

lista.extend(df_session_mayor_8_horas['id'].to_list())

#df_session_mayor_8_horas
lista 
df_sessions = df_sessions[~df_sessions['id'].isin(lista)]

promedio = df_sessions['duracion_session_horas'].mean()
df_session_mayor_8_horas
# df_sessions.head(20)
# 25
# 641
# 3
# 7
# 26
# 2791
# promedio = df_sessios['duracion_session_horas'].mean()
# promedio.round(2)

,id,user_id,start_time,end_time,status,conv_id,bot_feedback,agent_feedback,created_at,bot_phone_number,waiting_for_first_template_delivery,first_template_id,first_template_sent_time,scheduled_template_sent,scheduled_template_autosend_time,scheduled_template_to_be_sent,last_user_reply_time,duracion_session_min,duracion_session_horas
1,25,2,2025-10-22 21:01:15.447877+00:00,2025-10-23 13:50:48.339044+00:00,closed,198.0,NaN,NaN,2025-10-22 21:01:15.447884+00:00,6.372061e+14,False,None,NaT,None,NaT,None,NaT,1009.55,16.825833
2,641,326,2025-11-13 13:31:29.896718+00:00,2025-11-14 13:21:32.275703+00:00,closed,NaN,NaN,NaN,2025-11-13 13:31:29.896720+00:00,8.315141e+14,False,None,NaT,None,NaT,None,NaT,1430.04,23.834000
11,3,2,2025-09-30 15:28:20.048213+00:00,2025-10-01 15:02:42.910438+00:00,closed,175.0,NaN,NaN,2025-09-30 15:28:20.048216+00:00,NaN,False,None,NaT,None,NaT,None,NaT,1414.38,23.573000
15,7,1,2025-10-02 16:44:32.110896+00:00,2025-10-03 16:15:27.462783+00:00,closed,180.0,NaN,NaN,2025-10-02 16:44:32.110899+00:00,NaN,False,None,NaT,None,NaT,None,NaT,1410.92,23.515333
17,26,1,2025-10-23 00:09:51.667976+00:00,2025-10-23 12:51:48.609061+00:00,closed,199.0,5.0,5.0,2025-10-23 00:09:51.667980+00:00,6.372061e+14,False,None,NaT,None,NaT,None,NaT,761.95,12.699167
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6538,6595,3939,2026-01-14 20:52:35.076995+00:00,2026-01-15 13:36:27.055248+00:00,closed,6548.0,NaN,NaN,2026-01-14 20:52:35.076999+00:00,8.380580e+14,False,None,NaT,None,NaT,None,2026-01-15 13:24:30.480771+00:00,1003.87,16.731167
6571,6574,3924,2026-01-14 19:00:26.287124+00:00,2026-01-15 12:08:23.912511+00:00,closed,6527.0,NaN,NaN,2026-01-14 19:00:26.287126+00:00,8.315141e+14,False,None,NaT,None,NaT,None,2026-01-14 23:46:45.101638+00:00,1027.96,17.132667
6572,6439,3848,2026-01-13 19:22:43.188617+00:00,2026-01-14 19:23:48.207335+00:00,closed,6392.0,NaN,NaN,2026-01-13 19:22:43.188619+00:00,8.380580e+14,False,wamid.HBgMNTczMjE1MDE2NDg2FQIAERgSM0I3QTMxNDU2...,2026-01-13 19:22:43.691573+00:00,None,NaT,None,2026-01-14 19:17:47.880831+00:00,1441.08,24.018000
6595,6508,3887,2026-01-14 14:20:36.826045+00:00,2026-01-15 13:18:26.808342+00:00,closed,6461.0,NaN,NaN,2026-01-14 14:20:36.826048+00:00,8.380580e+14,False,wamid.HBgMNTczMjA3NjcwNDQwFQIAERgSNDJBMTU4MEFG...,2026-01-14 14:20:37.746960+00:00,None,NaT,None,2026-01-15 00:28:31.137079+00:00,1377.83,22.963833
6596,6622,3911,2026-01-14 23:46:16.933724+00:00,2026-01-15 13:18:27.109795+00:00,closed,6575.0,NaN,NaN,2026-01-14 23:46:16.933727+00:00,8.380580e+14,False,None,NaT,None,NaT,None,2026-01-14 23:56:58.363857+00:00,812.17,13.536167

In [196]:
df = pd.read_sql("SELECT * FROM conversation_context WHERE user_input IS NOT NULL OR system_input IS NOT NULL", engine)
df.head(25)

,id,session_id,state,user_input,system_input,timestamp
0,3215,41,debut,Hola,None,2025-10-24 14:36:27.957180+00:00
1,3217,41,main_menu,None,👨‍⚕️ Atención personalizada\n\n👋 ¡Hola! Bienve...,2025-10-24 14:36:27.957188+00:00
2,3218,41,main_menu,Ok,None,2025-10-24 14:39:04.976471+00:00
3,3220,41,handover,Hi,None,2025-10-24 14:39:28.456560+00:00
4,3221,41,handover,None,hola,2025-10-24 14:39:39.449634+00:00
5,3222,41,handover,Hola,None,2025-10-24 14:44:47.228238+00:00
6,3223,41,handover,Ok,None,2025-10-24 14:45:27.708134+00:00
7,3224,41,handover,None,hola locococo,2025-10-24 14:45:51.598455+00:00
8,3225,41,handover,Ok,None,2025-10-24 14:46:34.228072+00:00
9,306,3,debut,Hola,None,2025-09-30 15:28:21.002350+00:00
10,308,3,main_menu,None,👨‍⚕️ Atención personalizada\n\n👋 ¡Hola! Bienve...,2025-09-30 15:28:21.002358+00:00
11,309,3,main_menu,citas,None,2025-09-30 15:28:29.536130+00:00
12,102,1,debut,hola,None,2025-09-30 15:13:27.907086+00:00
13,104,1,main_menu,None,👨‍⚕️ Atención personalizada\n\n👋 ¡Hola! Bienve...,2025-09-30 15:13:27.907094+00:00
14,105,1,main_menu,citas,None,2025-09-30 15:13:35.516758+00:00
15,107,1,handover,hola,None,2025-09-30 15:15:07.349243+00:00
16,108,1,handover,None,re bien\n\n,2025-09-30 15:15:19.660998+00:00
17,109,1,handover,665071342893499,None,2025-09-30 15:16:00.074495+00:00
18,110,1,handover,783876914350078,None,2025-09-30 15:16:44.403824+00:00
19,111,1,handover,hola,None,2025-09-30 15:17:41.333017+00:00
20,112,1,handover,None,si listo pelao,2025-09-30 15:19:32.687899+00:00
21,113,1,handover,system_resolved,None,2025-09-30 15:19:39.912488+00:00
22,115,1,feedback,None,¿Cómo calificarías la atención del asesor?\n...,2025-09-30 15:19:39.912496+00:00
23,116,1,feedback,"{""agent_rating"":""5"",""flow_token"":""unused"",""bot...",None,2025-09-30 15:20:54.033507+00:00
24,118,1,final,None,"Gracias por contactar a Imagenes Diagnosticas,...",2025-09-30 15:20:54.033516+00:00

In [ ]:
df2 = pd.read_sql("SELECT * FROM essential_context ;", engine)
df2.head()

,id,session_id,situation,user_intent,user_data,timestamp
0,1,1,el sistema le presento al usuario el menu prin...,intencion commercial: el usuario desea agendar...,None,2025-09-30 15:13:35.515969+00:00
1,2,3,el sistema le presento al usuario el menu prin...,intencion commercial: el usuario desea agendar...,None,2025-09-30 15:28:29.535441+00:00
2,3,2,el sistema le presento al usuario el menu prin...,"intencion commercial: no hay intencion clara, ...",None,2025-09-30 15:28:35.245198+00:00
3,4,4,el sistema le presento al usuario el menu prin...,intencion commercial: el usuario desea saber s...,None,2025-09-30 16:07:25.683059+00:00
4,5,5,el sistema le presento al usuario el menu prin...,"intencion commercial: no hay intencion clara, ...",None,2025-09-30 19:13:36.719521+00:00

In [159]:
df3 = pd.read_sql("SELECT * FROM messages", engine)
df3.head(25)

,id,session_id,sender,message_type,content,media_path,timestamp
0,1,1,customer,text,hola,None,2025-09-30 15:13:27.147721+00:00
1,2,1,customer,text,citas,None,2025-09-30 15:13:35.511078+00:00
2,3,1,customer,text,hola,None,2025-09-30 15:15:07.343956+00:00
3,4,1,customer,text,665071342893499,None,2025-09-30 15:16:00.069715+00:00
4,5,1,customer,text,783876914350078,None,2025-09-30 15:16:44.399017+00:00
5,6,1,customer,text,hola,None,2025-09-30 15:17:41.328509+00:00
6,7,1,customer,text,"{""agent_rating"":""5"",""flow_token"":""unused"",""bot...",None,2025-09-30 15:20:53.356024+00:00
7,8,2,customer,text,Hola,None,2025-09-30 15:28:19.620239+00:00
8,9,3,customer,text,Hola,None,2025-09-30 15:28:20.049041+00:00
9,10,3,customer,text,citas,None,2025-09-30 15:28:29.530297+00:00
10,11,2,customer,text,No entiendo,None,2025-09-30 15:28:35.240115+00:00
11,12,3,customer,text,2227877501062897,None,2025-09-30 15:30:06.827624+00:00
12,13,3,customer,text,24672739125687663,None,2025-09-30 15:32:05.274056+00:00
13,14,2,customer,text,"{""agent_rating"":""5"",""bot_rating"":""5"",""flow_tok...",None,2025-09-30 16:07:04.047862+00:00
14,15,4,customer,text,Hola,None,2025-09-30 16:07:18.253651+00:00
15,16,4,customer,text,resultados,None,2025-09-30 16:07:25.678257+00:00
16,17,4,customer,text,1372037684524643,None,2025-09-30 16:07:38.607485+00:00
17,18,4,customer,text,1110489624581956,None,2025-09-30 16:07:45.486125+00:00
18,19,4,customer,text,"{""bot_rating"":""5"",""agent_rating"":""5"",""flow_tok...",None,2025-09-30 16:08:17.148698+00:00
19,20,5,customer,text,Hola,None,2025-09-30 18:30:41.944971+00:00
20,21,5,customer,text,Qué,None,2025-09-30 19:13:36.716972+00:00
21,22,5,customer,text,"{""agent_rating"":""1"",""bot_rating"":""1"",""flow_tok...",None,2025-09-30 20:45:42.890949+00:00
22,23,6,customer,text,Hola,None,2025-10-02 13:38:34.281704+00:00
23,24,6,customer,text,servicios,None,2025-10-02 13:38:49.112277+00:00
24,25,6,customer,text,1132521422313240,None,2025-10-02 13:40:12.501091+00:00

In [149]:
prueba = df3['timestamp']
prueba

0       2025-09-30 15:13:27.147721+00:00
1       2025-09-30 15:13:35.511078+00:00
2       2025-09-30 15:15:07.343956+00:00
3       2025-09-30 15:16:00.069715+00:00
4       2025-09-30 15:16:44.399017+00:00
                      ...
45094   2026-01-15 13:47:26.438685+00:00
45095   2026-01-15 13:47:32.075548+00:00
45096   2026-01-15 13:48:07.082819+00:00
45097   2026-01-15 13:48:08.590953+00:00
45098   2026-01-15 13:48:08.676886+00:00
Name: timestamp, Length: 45099, dtype: datetime64[ns, UTC]